Repository woowacourse-teams/2023-car-ffeine, pull requests merged in 2023-10, with the labels that each got.

#817 feat: 주요 도시에 대표 마커를 렌더링한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/marker/CityClusteredMarkersContainer/CityClusteredMarkersContainer.tsx
  frontend/src/components/google-maps/marker/CityClusteredMarkersContainer/index.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/HighZoomMarkerContainer.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeine.stories.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.style.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.test.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/index.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/hooks/useStationMarkers.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/components/RegionMarker.stories.tsx
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/components/RegionMarker.tsx
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/components/RegionMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/hooks/useRegionMarkers.ts
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/hooks/useRenderRegionMarker.tsx
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/types/index.ts
  frontend/src/components/google-maps/marker/MarkersContainers.tsx
  frontend/src/components/google-maps/marker/MiddleZoomMarkerContainer/MiddleZoomMarkerContainer.tsx
  frontend/src/components/google-maps/marker/MiddleZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/ServerClusteredMarkersContainer/ServerClusteredMarkersContainer.tsx
  frontend/src/components/google-maps/marker/ServerClusteredMarkersContainer/index.ts
  frontend/src/components/google-maps/marker/StationMarkersContainer/index.ts
  frontend/src/components/ui/CarFfeineMarker/index.ts
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/station-markers/stationMarkerHandlers.ts
  frontend/src/stores/google-maps/googleMapStore.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.ts
Labels: 🛠️ 리팩터링, FE

#824 refactor: 좌측 패널의 충전소 리스트의 사용성을 개선한다
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCardList.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/EmptyStationsNotice.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/StationListSkeletons.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/StationSummaryCardSkeleton.stories.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/StationSummaryCardSkeleton.tsx
  frontend/src/components/ui/StationListWindow/hooks/useFetchStationSummaries.ts
  frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
  frontend/src/components/ui/StationListWindow/index.ts
Labels: 🛠️ 리팩터링, FE

#830 feat: 특정 줌 레벨까지 마커의 크기를 줄여서 보여주는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/HighZoomMarkerContainer.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/constants/index.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/google-maps/marker/MarkersContainers.tsx
  frontend/src/components/google-maps/marker/MiddleZoomMarkerContainer/MiddleZoomMarkerContainer.tsx
  frontend/src/components/ui/StationInfoWindow/SummaryButtons.stories.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/hooks/google-maps/useStationInfoWindow.tsx
  frontend/src/stores/google-maps/markerInstanceStore.ts
  frontend/src/stores/google-maps/zoomStore/types.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.test.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.ts
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE

#832 design: infoWindow 디자인을 개선한다
  frontend/src/components/common/Box/Box.style.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Button/Button.style.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/ButtonNext/ButtonNext.style.ts
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/common/FlexBox/FlexBox.style.ts
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/List/List.style.ts
  frontend/src/components/common/List/List.tsx
  frontend/src/components/common/ListItem/ListItem.style.ts
  frontend/src/components/common/ListItem/ListItem.tsx
  frontend/src/components/common/Skeleton/Skeleton.style.ts
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/common/Text/Text.style.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/styles/spacing.ts
  frontend/src/components/common/systems.ts
  frontend/src/components/common/utils/addUnit.ts
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/constants/index.ts
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.stories.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/components/ui/StationInfoWindow/SummaryButtons.stories.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCard.tsx
  frontend/src/components/ui/StationSearchWindow/tools/convertStationDetailsToSummary.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#835 refactor: 줌 레벨에 따라 마커 컨테이너를 렌더링 하는 방식을 개선한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/HighZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/LargeDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/LowZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/MarkerContainers.tsx
  frontend/src/components/google-maps/marker/MarkersContainers.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/MaxDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarker.stories.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarker.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/hooks/useRegionMarkers.ts
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/hooks/useRenderRegionMarker.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/types/index.ts
  frontend/src/components/google-maps/marker/MiddleZoomMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/SmallMediumDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeine.stories.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.style.ts
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.test.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/index.ts
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/constants/index.ts
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/hooks/useStationMarkers.ts
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/index.ts
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/mocks/data.ts
  frontend/src/stores/google-maps/deltaAreaStore/deltaAreaStore.test.ts
  frontend/src/stores/google-maps/deltaAreaStore/deltaAreaStore.ts
  frontend/src/stores/google-maps/deltaAreaStore/index.ts
  frontend/src/stores/google-maps/deltaAreaStore/types.ts
  frontend/src/stores/google-maps/zoomStore/index.ts
  frontend/src/stores/google-maps/zoomStore/types.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.test.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.ts
Labels: 🛠️ 리팩터링, FE

#837 feat: 지역 검색 기능을 구현한다
  frontend/src/components/common/Button/Button.style.ts
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/ui/Error.tsx
  frontend/src/components/ui/StationSearchWindow/NoResult.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.style.ts
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/SearchedCityCard.tsx
  frontend/src/components/ui/StationSearchWindow/SearchedStationCard.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.style.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/hooks/tanstack-query/useSearchStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/stationSearchHandlers.ts
  frontend/src/types/stations.ts
Labels: 🌱 기능추가, FE, 🦜 UI

#840 design: 모달 디자인을 개선한다
  frontend/public/favicon.ico
  frontend/public/icons/114.png
  frontend/public/icons/120.png
  frontend/public/icons/144.png
  frontend/public/icons/152.png
  frontend/public/icons/16.png
  frontend/public/icons/180.png
  frontend/public/icons/192.png
  frontend/public/icons/32.png
  frontend/public/icons/36.png
  frontend/public/icons/48.png
  frontend/public/icons/512.png
  frontend/public/icons/57.png
  frontend/public/icons/60.png
  frontend/public/icons/72.png
  frontend/public/icons/76.png
  frontend/public/icons/96.png
  frontend/public/icons/ios/apple-icon-114x114.png
  frontend/public/icons/ios/apple-icon-120x120.png
  frontend/public/icons/ios/apple-icon-144x144.png
  frontend/public/icons/ios/apple-icon-152x152.png
  frontend/public/icons/ios/apple-icon-180x180.png
  frontend/public/icons/ios/apple-icon-57x57.png
  frontend/public/icons/ios/apple-icon-60x60.png
  frontend/public/icons/ios/apple-icon-72x72.png
  frontend/public/icons/ios/apple-icon-76x76.png
  frontend/public/index.html
  frontend/src/assets/logo-md.svg
  frontend/src/assets/logo-sm.svg
  frontend/src/assets/logo.svg
  frontend/src/components/common/utils/addUnit.ts
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.tsx
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#844 fix: flyway 문법을 수정한다
  backend/src/main/resources/db/migration/V10__add_city.sql
Labels: 🚑 버그, BE

#846 fix: 대도시 마커 렌더링 오류를 수정한다
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/hooks/useRegionMarkers.ts
  frontend/src/mocks/handlers/station-markers/stationMarkerHandlers.ts
Labels: 🚑 버그, FE, 🚨 긴급

#848 feat: 404 페이지 구현 및 공통 컴포넌트 마이그레이션한다
  frontend/.storybook/preview.tsx
  frontend/src/assets/not-found.svg
  frontend/src/components/common/Box/Box.style.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.style.ts
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/Text/Text.style.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/styles/common.ts
  frontend/src/components/common/styles/spacing.ts
  frontend/src/components/common/types/base.ts
  frontend/src/components/common/utils/addUnit.ts
  frontend/src/components/ui/ChargingSpeedIcon.tsx
  frontend/src/components/ui/NotFound/NotFound.stories.tsx
  frontend/src/components/ui/NotFound/NotFound.tsx
  frontend/src/components/ui/NotFound/index.ts
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.stories.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/components/ui/StationSearchWindow/SearchedStationCard.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/BarContainer.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.tsx
  frontend/src/router/index.tsx
  frontend/src/style/GlobalStyle.ts
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE, 🦜 UI

#854 design: 충전소 리스트 에러 컴포넌트 및 사소한 디자인 개선한다
  frontend/src/assets/loading.svg
  frontend/src/assets/logo-icon.svg
  frontend/src/assets/nothing.svg
  frontend/src/components/common/Box/Box.style.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Button/Button.style.ts
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/NotFound/NotFound.tsx
  frontend/src/components/ui/ShowHideButton.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsViewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Title.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformationSkeleton.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationListWindow/StationListWindow.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/EmptyStationsNotice.stories.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/EmptyStationsNotice.tsx
  frontend/src/components/ui/StationSearchWindow/SearchedCityCard.tsx
  frontend/src/components/ui/StationSearchWindow/SearchedStationCard.tsx
  frontend/src/components/ui/Svg/LogoIcon.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.stories.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/stores/google-maps/stationInfoWindowStore.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#842 design: 서버 클러스터링 마커 디자인을 구현한다
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarker.stories.tsx
  frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
  frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.tsx
Labels: FE, 🦜 UI

#855 feat: 클러스터 mock api 구현
  frontend/src/mocks/handlers/clustering/clusteringHandler.ts
Labels: 🌱 기능추가, FE

#856 feat: 서버 클러스터링 마커를 렌더링한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/LargeDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/FooMarker.stories.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/FooMarker.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useClusterMarkers.ts
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useRenderClusterMarker.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/SmallMediumDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/google-maps/useStationInfoWindow.tsx
  frontend/src/mocks/handlers/clustering/clusteringHandler.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/stores/google-maps/markerInstanceStore.ts
  frontend/src/types/stations.ts
Labels: 🌱 기능추가, FE

#857 refactor: indexedDB를 활용하여 msw용 mocking 데이터 생성 구조를 개선한다
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/modal/DeveloperModeModal.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/data/cars.ts
  frontend/src/mocks/data/congestions.ts
  frontend/src/mocks/data/regions.ts
  frontend/src/mocks/data/reviews.ts
  frontend/src/mocks/data/search.ts
  frontend/src/mocks/data/stations.ts
  frontend/src/mocks/handlers/car/carHandler.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
  frontend/src/mocks/handlers/station-details/stationDetailHandlers.ts
  frontend/src/mocks/handlers/station-details/statisticsHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationMarkerHandlers.ts
  frontend/src/mocks/handlers/stationSearchHandlers.ts
  frontend/src/utils/IndexedDBUtil.ts
Labels: 🛠️ 리팩터링, FE

#862 design: 사용량이 높을 수록 빨간색이 보이도록 그래프 개선한다
  frontend/src/components/ui/StationDetailsWindow/congestion/bar/Bar.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/bar/Bars.stories.tsx
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#864 fix: 사용량 통계 부분 렌더링을 개선한다
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/src/components/ui/StationDetailsWindow/congestion/ChargingSpeedButtons.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/StatisticsContent.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/tools/getChargerCountsAndAvailability.ts
  frontend/tsconfig.json
  frontend/webpack.config.dev.js
Labels: 🚑 버그, 🛠️ 리팩터링, FE

#866 fix: 주변 충전소가 없습니다 컴포넌트 잘리는 문제 개선한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/ui/StationListWindow/fallbacks/EmptyStationsNotice.tsx
Labels: 🚑 버그, FE, 🦜 UI

#869 fix: 절대 경로 추가하여 빌드 오류를 개선한다
  frontend/webpack.config.prod.js
Labels: 🚑 버그, FE, 🚨 긴급

#870 refactor: 마커 애니메이션을 추가한다
  frontend/public/index.html
  frontend/src/components/common/Skeleton/Skeleton.style.ts
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/LargeDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useClusterMarkers.ts
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useRenderClusterMarker.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/hooks/useRenderRegionMarker.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/bar/Bar.tsx
  frontend/src/constants/storageKeys.ts
  frontend/src/mocks/data/regions.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#873 fix: 서버 클러스터링 캐싱에 의해 줌 레벨 변화에 재 요청을 보내지 않는 오류를 수정한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/stores/google-maps/googleMapStore.ts
Labels: 🚑 버그, FE

#876 refactor: 서버 클러스터 마커 디자인을 개선합니다.
  frontend/src/components/common/FlexBox/FlexBox.style.ts
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/FooMarker.stories.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/FooMarker.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/StyledClusterMarker.stories.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/StyledClusterMarker.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useClusterMarkers.ts
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useRenderClusterMarker.tsx
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#878 fix: 로그인 에러를 개선한다
  frontend/src/router/index.tsx
Labels: 🚑 버그, FE, 🚨 긴급

#884 fix: 서버 클러스터 마커를 클릭했을 때 충전소 마커가 나오지 않고 위치만 이동하는 오류를 개선한다
  frontend/src/constants/googleMaps.ts
  frontend/src/stores/google-maps/deltaAreaStore/deltaAreaStore.test.ts
Labels: 🚑 버그, FE, 🚨 긴급

#881 feat: 길찾기 기능을 구현한다
  frontend/src/components/ui/StationInfoWindow/PathFinding.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/components/ui/StationInfoWindow/SummaryButtons.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
Labels: 🌱 기능추가, FE

#888 refactor: 서버 클러스링 마커 클릭 시 줌을 적당하게 확대하도록 개선한다
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useRenderClusterMarker.tsx
Labels: 🛠️ 리팩터링, FE

#889 refactor: StationInfoWindow의 Layout Shift 현상을 제거한다
  frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
Labels: 🚑 버그, FE, 🦜 UI

#896 refactor: 차량 선택 기능 진입 버튼을 제거한다
  frontend/src/components/ui/Navigator/NavigationBar/PersonalMenu.tsx
  frontend/src/components/ui/Navigator/Navigator.test.tsx
Labels: 🚑 버그, FE, 🚨 긴급

#891 feat: 카페인 공통 컴포넌트 분리 후 npm 배포한 것 사용한다
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE

#875 feat: 무중단 배포를 위해 스크립트를 수정합니다
  .github/workflows/backend-deploy.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  shellscript/bluegreen.sh
Labels: BE

#898 feat: 메뉴 토글 기능 구현한다
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/Navigator/NavigationBar/hooks/useNavigationBar.ts
Labels: 🌱 기능추가, FE

#886 refactor: husky를 개선한다
  frontend/.gitignore
  frontend/.husky/commit-msg
  frontend/.husky/pre-commit
  frontend/package.json
  frontend/readme.md
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE

#900 refactor: 앱 설치 버튼 구현 및 버튼 누르면 나오는 설치 방법 설명 모달 구현한다
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/pwabuilder-sw.js
  frontend/src/App.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/StyledClusterMarker.tsx
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/HowToAppInstallModal.tsx
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE

#905 chore: 일부 dependencies를 devDependencies로 이전한다
  README.md
  frontend/package.json
  frontend/src/components/ui/Navigator/ProfileMenu/Menus.tsx
  frontend/src/components/ui/Navigator/ProfileMenu/ProfileMenu.tsx
Labels: FE

#907 refactor: 폰트 로딩을 최적화한다
  frontend/public/index.html
Labels: 🛠️ 리팩터링, FE

#880 feat: 대한민국을 2km단위로 나눠 해당 지역의 충전소 개수를 계산한다
  backend/src/README.md
  backend/src/main/java/com/carffeine/carffeine/station/config/InitialStationGridLoader.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Grid.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/GridGenerator.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Latitude.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Longitude.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Point.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Region.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationPoint.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridCacheService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridFacadeService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/ClusterRequest.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/GridWithCount.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/GridGeneratorTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/GridTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/LatitudeTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationGridServiceTest.java
Labels: 🌱 기능추가, BE

#909 fix: 폰트 preload 에러를 개선한다
  frontend/public/index.html
Labels: 🚑 버그, FE, 🚨 긴급

#917 fix: 데스크톱 모드에서 충전소 상세정보 보기 버튼이 항상 보여지는 문제를 수정한다
  frontend/src/components/ui/Navigator/NavigationBar/hooks/useNavigationBar.ts
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
Labels: 🚑 버그, FE
