Repository woowacourse-teams/2023-car-ffeine, pull requests merged in 2023-07, with the labels that each got.

#2 feat: pr 템플릿과, issue template 을 작성한다
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#10 feat: Rest Docs를 적용한다.
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/test.adoc
  backend/src/test/java/com/carffeine/carffeine/helper/RestDocsHelper.java
Labels: 문서, 개선사항, 백엔드

#6 feat: pr 을 생성했을 때 issue 자동 연동 기능 추가
  .github/workflows/assign_issue_to_pr.yml
Labels: 문서, 개선사항, 백엔드, 프론트엔트

#17 design: 크로스 브라우징을 위해 스타일을 초기화한다
  frontend/src/index.tsx
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/reset.ts
Labels: 프론트엔드, UI

#18 feat: 공공 API 데이터를 저장하는 기능을 구현한다
  backend/src/main/java/com/carffeine/carffeine/CarffeineApplication.java
  backend/src/main/java/com/carffeine/carffeine/config/RestTemplateConfig.java
  backend/src/main/java/com/carffeine/carffeine/domain/ChargeStation.java
  backend/src/main/java/com/carffeine/carffeine/domain/ChargeStationRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/ChargerId.java
  backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationRequest.java
  backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationsInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
  backend/src/test/java/com/carffeine/carffeine/CarffeineApplicationTests.java
  backend/src/test/java/com/carffeine/carffeine/service/ScrapperServiceTest.java
Labels: 기능추가, BE

#35 feat: 현재 위치를 초기 좌표로 설정하는 기능을 구현한다
  frontend/src/components/GoogleMap.tsx
  frontend/src/hooks/useCurrentPosition.tsx
Labels: 기능추가, FE, 페어

#37 feat: 지도 위 현재 내 위치에 마커를 표시한다
  frontend/src/App.tsx
  frontend/src/components/GoogleMap.tsx
  frontend/src/components/map/CarFfeineMap.tsx
  frontend/src/components/marker/UserMarker.tsx
  frontend/src/hooks/useCurrentPosition.tsx
  frontend/src/types/index.ts
Labels: 기능추가, FE, 페어

#48 chore: prettier 버전 업데이트 및 수정한다
  frontend/.prettierrc
  frontend/package.json
  frontend/src/components/map/CarFfeineMap.tsx
  frontend/yarn.lock
Labels: FE

#51 feat: 전역 상태 관리 유틸을 구현한다
  frontend/src/utils/external-state/StateManager.ts
  frontend/src/utils/external-state/index.ts
  frontend/src/utils/external-state/tools.ts
Labels: 기능추가, FE, 페어

#43 feat: 데이터 암호화 기능을 추가한다
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
  backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: BE

#56 feat: msw로 충전소 데이터를 mocking하는 기능을 구현한다
  frontend/src/components/marker/UserMarker.tsx
  frontend/src/hooks/useCurrentPosition.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/types/index.ts
Labels: 기능추가, FE, 페어

#57 feat: TanStack Query를 사용하여 충전소 마커를 찍는다
  frontend/package.json
  frontend/src/components/map/CarFfeineMap.tsx
  frontend/src/components/marker/StationMarker.tsx
  frontend/src/components/marker/StationMarkersContainer.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/types/index.ts
  frontend/src/utils/google-maps/index.ts
  frontend/yarn.lock
Labels: 기능추가, FE, 페어

#55 feat: CODEOWNERS 파일 작성
  .github/CODEOWNERS
Labels: 기능추가, BE, FE

#63 style: prettier 적용 안 된 파일에 prettier를 적용한다
  frontend/src/hooks/useCurrentPosition.ts
  frontend/src/utils/external-state/StateManager.ts
  frontend/src/utils/external-state/tools.ts
Labels: FE

#54 feat: logger error 마다 슬랙으로 발생하는 로그를 전송한다
  backend/src/main/java/com/carffeine/carffeine/log/SlackAppender.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: 기능추가, BE

#68 feat: google maps api와 react UI를 연동한다
  frontend/src/App.tsx
  frontend/src/components/BriefStationInfo.tsx
  frontend/src/components/googleMaps/map/CarFfeineMap.tsx
  frontend/src/components/googleMaps/marker/StationMarker.tsx
  frontend/src/components/googleMaps/marker/StationMarkersContainer.tsx
  frontend/src/components/googleMaps/marker/UserMarker.tsx
  frontend/src/components/marker/StationMarker.tsx
  frontend/src/components/marker/StationMarkersContainer.tsx
Labels: 기능추가, FE, 페어

#72 refactor: msw 및 데이터를 개선한다
  frontend/src/components/BriefStationInfo.tsx
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/types/index.ts
Labels: 리팩터링, FE

#74 refactor: 코드 가독성을 증진시킨다
  frontend/src/components/googleMaps/map/CarFfeineMap.tsx
  frontend/src/components/googleMaps/marker/StationMarker.tsx
  frontend/src/components/googleMaps/marker/StationMarkersContainer.tsx
  frontend/src/components/googleMaps/marker/UserMarker.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/hooks/useUpdateStations.ts
  frontend/src/types/index.ts
  frontend/src/utils/google-maps/index.ts
Labels: 리팩터링, FE, 페어

#77 refactor: scrap 메서드를 리팩터링 한다
  backend/.gitignore
  backend/src/main/java/com/carffeine/carffeine/config/InitialChargeStationLoader.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStation.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/CustomChargeStationRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/Latitude.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/Longitude.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/charger/CustomChargerRepository.java
  backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargerRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationsInfoRequest.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/domain/chargerStation/charger/LongitudeTest.java
  backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
  backend/src/test/java/com/carffeine/carffeine/service/ScrapperServiceTest.java
  backend/src/test/resources/application.yml
Labels: 리팩터링, BE

#82 feat: 서버로부터 수신 받은 충전소 데이터를 충전소 목록으로 보여주는 컴포넌트를 구현한다
  .gitignore
  frontend/src/App.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/google-maps/marker/UserMarker.tsx
  frontend/src/components/googleMaps/marker/StationMarker.tsx
  frontend/src/components/googleMaps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/BriefStationInfo.tsx
  frontend/src/components/ui/MarkerList.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/stores/briefStationInfoWindowStore.ts
  frontend/src/stores/googleMapStore.ts
  frontend/src/stores/markerIntanceStore.ts
  frontend/src/utils/external-state/tools.ts
Labels: 기능추가, FE, 페어

#92 refactor: briefStationInfoWindowStore 모듈화
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/stores/briefStationInfoWindowStore.ts
Labels: 리팩터링, FE

#85 feat: pull request 시 gradle test가 동작하도록 설정한다
  .github/workflows/backend-test-when-pr.yml
Labels: 기능추가, BE

#94 rename: 파일명에 있는 오타를 수정한다
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/MarkerList.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/stores/googleMapStore.ts
  frontend/src/stores/markerInstanceStore.ts
Labels: FE, 사소한 수정

#96 chore: prettier로 import 부분을 정리한다
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/BriefStationInfo.tsx
  frontend/src/components/ui/MarkerList.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/hooks/useCurrentPosition.ts
  frontend/src/hooks/useStations.ts
  frontend/src/hooks/useUpdateStations.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/stores/briefStationInfoWindowStore.ts
  frontend/src/stores/googleMapStore.ts
  frontend/src/stores/markerInstanceStore.ts
  frontend/src/utils/external-state/tools.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 리팩터링, FE

#99 feat: 지도를 확대/축소하는 버튼 구현
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ZoomController.tsx
  frontend/src/stores/googleMapStore.ts
Labels: 기능추가, FE

#97 feat: 서비스 Key 자동 선택 기능 추가
  backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
  backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ChargerStationService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/ChargeStationsInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/CoordinateRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/RandomKeySelector.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/fixture/chargerstation/ChargerFixture.java
  backend/src/test/java/com/carffeine/carffeine/integration/chargestation/ChargerStationIntegrationTestFixture.java
  docker-compose.yml
Labels: 기능추가, BE

#69 feat: 혼잡도를 저장하는 기능을 구현한다
  backend/src/docs/asciidoc/station.adoc
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/CongestionInfoResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/CongestionResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/StatisticsResponse.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/IdGenerator.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/PeriodicCongestion.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/PeriodicCongestionRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/RequestPeriod.java
  backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ChargerStationService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargeStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/CongestionService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ScrapperService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargeStationInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargeStationRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargeStationsInfoRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargersForCongestionRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/CoordinateRequest.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/Item.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/Items.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/RandomKeySelector.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/StatisticsRequest.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/controller/chargerStation/ChargerStationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargerStation/congestion/RequestPeriodTest.java
  backend/src/test/java/com/carffeine/carffeine/service/chargerstation/ChargerStationServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/service/chargerstation/CongestionServiceTest.java
Labels: 기능추가, BE

#101 refactor: useExternalState의 setState를 개선한다
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/utils/external-state/StateManager.ts
  frontend/src/utils/external-state/tools.ts
Labels: 리팩터링, FE

#109 feat: 버튼 스타일 컴포넌트를 구현한다
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/src/components/common/Button/Button.stories.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Button/index.ts
Labels: 기능추가, FE, UI, 페어

#111 refactor: google map을 전달하는 구조를 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/stores/googleMapStore.ts
Labels: 리팩터링, FE

#117 test: 필요없는 파일을 제거하고 스토리북 기본 형식을 변경한다
  frontend/src/components/common/Button/Button.stories.ts
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: 리팩터링, FE

#118 feat: 현위치 버튼 클릭 시 현위치로 복귀하는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ZoomController.tsx
Labels: 기능추가, FE

#122 chore: 마커 커스텀을 위한 svg import 환경을 설정한다
  frontend/.prettierrc
  frontend/jest.config.json
  frontend/package.json
  frontend/src/assets/blue-marker.svg
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/types/assets.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 리팩터링, FE

#126 chore: 커밋시 프리티어와 eslint 적용을 자동화한다
  frontend/.husky/pre-commit
  frontend/package.json
  frontend/src/components/common/Button/Button.stories.ts
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/yarn.lock
Labels: 기능추가, FE

#124 feat: 충전소 마커를 필터링 하는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/FilterButtonList.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/mocks/data.ts
  frontend/src/stores/stationFilterStore.ts
  frontend/src/utils/external-state/StateManager.ts
  frontend/src/utils/external-state/tools.ts
Labels: 기능추가, FE

#133 fix: prettier 자동화와 이슈 번호 자동화가 동시에 적용되지 않는 에러를 개선한다
  frontend/.husky/commit-msg
Labels: 버그, FE, 긴급

#132 feat: 간단 정보 띄우는 기능을 구현한다
  frontend/src/components/ui/BriefStationInfo.tsx
Labels: 기능추가, FE

#134 feat: 마지막 접속한 이력이 있는 클라이언트라면 마지막 위치를 우선하여 지도를 로드하는 기능을 추가한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useCurrentPosition.ts
  frontend/src/stores/googleMapStore.ts
  frontend/src/types/index.ts
  frontend/src/utils/storage/index.ts
  frontend/src/utils/storage/keys.ts
Labels: 리팩터링, 기능추가, FE

#137 fix: husky가 mac에서 작동하지 않는 오류를 개선한다
  frontend/package.json
Labels: 버그, FE, 긴급

#138 fix: 웹팩 빌드 오류를 해결한다
  frontend/src/index.tsx
  frontend/src/style/GlobalStyle.ts
Labels: 버그, FE, 긴급

#141 fix: 위도, 경도 기반으로 조회 시 위도가 잘못되는 버그를 해결한다
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStationRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerStatus.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationService.java
Labels: 버그, BE, 긴급

#147 fix: 몇몇 패키지를 devDenpencies에서 dependencies으로 이동한다
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: 버그, 리팩터링, FE, 긴급

#150 feat: App을 import 하기 전에 구글 맵 키를 반드시 입력해야 실행이 되도록 하는 기능 구현
  frontend/src/App.tsx
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/index.tsx
  frontend/src/utils/storage/keys.ts
Labels: 기능추가, FE, 긴급

#155 feat: 충전소 상세 정보 보여주는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/BriefStationInfo.tsx
  frontend/src/components/ui/DetailedStationInfo.tsx
  frontend/src/components/ui/FilterButtonList.tsx
  frontend/src/components/ui/MarkerList.tsx
  frontend/src/components/ui/StationList.tsx
  frontend/src/hooks/useChangeStationDetails.ts
  frontend/src/hooks/useSelectedStation.ts
  frontend/src/hooks/useStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/selectedStationStore.ts
  frontend/src/types/index.ts
Labels: 기능추가, FE

#127 feat: Github Actions Self Hosted Runner를 위해 workflow 파일을 생성한다
  .github/workflows/backend-deploy.yml
  backend/Dockerfile
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: BE

#151 feat: 충전기와 충전소를 주기적으로 업데이트하는 기능을 구현한다
  backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargeStationSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargeStationSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargeStationsSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargerSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargerSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStation.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStationRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/CustomChargeStationRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/Latitude.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/Longitude.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerRepository.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerState.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerStatus.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/CustomChargerRepository.java
  backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargerRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargeStationPeriodicUpdateService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/CongestionService.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargeStationInfoRequest.java
  backend/src/test/java/com/carffeine/carffeine/controller/chargerStation/ChargerStationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargestation/ChargeStationTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargestation/CustomChargeStationRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargestation/charger/CustomChargerRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/domain/chargestation/congestion/RequestPeriodTest.java
  backend/src/test/java/com/carffeine/carffeine/fake/chargerstation/FakeChargeStationRepository.java
  backend/src/test/java/com/carffeine/carffeine/fixture/chargerstation/ChargeStationFixture.java
  backend/src/test/java/com/carffeine/carffeine/fixture/chargerstation/ChargerFixture.java
  backend/src/test/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateServiceTest.java
  backend/src/test/resources/application.yml
Labels: 기능추가, BE

#153 refactor: capacity가 없을 경우 기본값을 정한다
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargerSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/controller/chargerStation/dto/ChargerSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerType.java
  backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargerRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/ChargeStationInfoRequest.java
  backend/src/test/java/com/carffeine/carffeine/fixture/chargerstation/ChargerFixture.java
Labels: 리팩터링, BE, 긴급

#159 refactor: 실제 api와 클라이언트를 연결해본다
  frontend/src/hooks/useStations.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers.ts
Labels: 리팩터링, BE, FE, 페어

#162 fix: 암호화 방법과 디코딩 키 변경 및 flyway 제거
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: BE, 사소한 수정

#163 refactor: 서버 주소 추가 및 서버가 주는 정보에 맞춰 코드 변경한다
  frontend/package.json
  frontend/src/constants/index.ts
  frontend/src/hooks/useSelectedStation.ts
  frontend/src/hooks/useStations.ts
  frontend/src/mocks/handlers.ts
Labels: 리팩터링, FE, 페어

#152 feat: FE의 CD 를 구축한다
  .github/workflows/frontend-deploy.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: 기능추가, FE

#145 feat: 텍스트 스타일 컴포넌트를 제작한다
  frontend/.husky/commit-msg
  frontend/.husky/pre-commit
  frontend/public/index.html
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/Text/index.ts
  frontend/src/style/GlobalStyle.ts
Labels: 기능추가, FE, UI

#166 refactor: template에 예상 소요 시간, 실제 소요 시간을 추가한다
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서, 리팩터링, BE, FE

#173 feat: 플렉스 박스 스타일 컴포넌트를 구현한다
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/package.json
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/FlexBox/index.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/style/index.ts
  frontend/src/types/style.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 기능추가, FE

#178 refactor: FlexBox에 width, height 속성을 추가한다
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
Labels: 리팩터링, FE

#190 fix: @style 경로를 참조할 수 없는 에러를 개선한다
  frontend/webpack.config.js
Labels: 버그, FE, 긴급

#188 feat: 충전소 정보 서버 필터링 api를 mocking한다
  frontend/src/components/ui/DetailedStationInfo.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/utils/request-query-params/index.ts
Labels: 기능추가, FE

#191 feat: 네비게이터 컴포넌트를 구현한다
  frontend/src/assets/filter-icon.svg
  frontend/src/assets/list-menu-icon.svg
  frontend/src/assets/logo-icon.svg
  frontend/src/assets/search-icon.svg
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/Navigator.tsx
  frontend/src/components/ui/StationList.tsx
Labels: 기능추가, FE, UI

#193 feat: 실시간 필터링 옵션에 외부인 사용 가능 여부 필터링 옵션을 추가한다
  frontend/src/components/ui/FilterButtonList.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/stores/stationFilterStore.ts
Labels: 기능추가, FE

#194 refactor: Text variant type 지정
  frontend/src/components/common/Text/Text.tsx
Labels: 리팩터링, FE, UI, 긴급

#196 feat: 충전소를 고장 신고하는 기능을 구현한다
  backend/src/docs/asciidoc/report.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/ReportController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/FaultReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/FaultReportRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Station.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/report/ReportException.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/report/ReportExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/station/service/report/ReportService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/report/FakeFaultRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/report/FaultReportRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/report/ReportServiceTest.java
Labels: 기능추가, BE

#197 feat: List와 ListItem 컴포넌트를 구현한다
  frontend/src/components/common/List/List.stories.tsx
  frontend/src/components/common/List/List.tsx
  frontend/src/components/common/List/index.ts
  frontend/src/components/common/ListItem/ListItem.stories.tsx
  frontend/src/components/common/ListItem/ListItem.tsx
  frontend/src/components/common/ListItem/index.ts
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.tsx
Labels: 기능추가, FE, UI

#199 feat: 사용자 식별이 가능하도록 토큰을 생성하는 기능 구현
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/constants/index.ts
  frontend/src/index.tsx
  frontend/src/stores/googleMapStore.ts
  frontend/src/utils/configureToken.ts
  frontend/src/utils/storage/keys.ts
Labels: 기능추가, FE

#205 refactor: 절대 경로를 확장성 있게 수정한다
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 리팩터링, FE

#215 feat: develop mode에서 msw와 로컬 서버를 동적으로 선택하는 기능을 구현한다
  frontend/readme.md
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/Navigator.tsx
  frontend/src/index.tsx
  frontend/src/mocks/configureMsw.ts
Labels: 리팩터링, 기능추가, FE, 긴급

#207 feat: 서버 필터링 옵션을 선택하는 UI를 구현한다
  frontend/package.json
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo.tsx
  frontend/src/components/ui/Navigator.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/index.ts
  frontend/src/components/ui/StationList.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useServerStationFilters.ts
  frontend/src/hooks/useStations.ts
  frontend/src/hooks/useUpdateStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/selectedServerStationFiltersStore.ts
  frontend/src/stores/serverStationFiltersOpenStore.ts
  frontend/src/types/index.ts
  frontend/src/utils/request-query-params/index.ts
Labels: 기능추가, FE, UI

#219 feat: Box 컴포넌트를 구현한다
  frontend/src/components/common/Box/Box.stories.tsx
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Box/index.ts
Labels: 기능추가, FE, UI

#201 feat: 고장 신고 여부를 확인하는 기능을 구현한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/ReportController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/dto/DuplicateReportResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/service/report/ReportService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/report/FaultReportRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/report/ReportServiceTest.java
Labels: 기능추가, BE

#222 feat: TextField를 구현한다
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/TextField/TextField.stories.tsx
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/common/TextField/index.ts
Labels: 기능추가, FE, UI

#221 feat: 검색창 컴포넌트를 구현한다
  frontend/src/assets/search.svg
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/ListItem/ListItem.stories.tsx
  frontend/src/components/common/ListItem/ListItem.tsx
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/ui/SearchResult/SearchResult.stories.tsx
  frontend/src/components/ui/SearchResult/SearchResult.tsx
  frontend/src/components/ui/SearchResult/index.ts
  frontend/src/components/ui/StationSearchBar/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchBar/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchBar/index.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/components/ui/StationSearchWindow/index.ts
  frontend/src/style/index.ts
Labels: FE, UI

#223 feat: 누적 혼잡도 통계를 시각화 해주는 컴포넌트를 개발한다
  frontend/.husky/commit-msg
  frontend/.husky/pre-commit
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StatisticsGraph/DaySelectButton.tsx
  frontend/src/components/ui/StatisticsGraph/GraphBar.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.tsx
  frontend/src/components/ui/StatisticsGraph/index.ts
  frontend/src/constants/index.ts
  frontend/src/mocks/data.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/types/index.ts
Labels: 기능추가, FE, UI

#227 feat: pr시 comment에 스토리북 배포 링크를 자동으로 달아주는 기능을 구현한다
  .github/workflows/frontend-storybook-deploy.yml
Labels: 기능추가, BE, FE, 페어

#231 feat: 검색창 렌더링 기능을 구현하고 웹 접근성 요소를 추가한다
  frontend/.gitignore
  frontend/src/assets/filter-icon.svg
  frontend/src/assets/list-menu-icon.svg
  frontend/src/assets/search-icon.svg
  frontend/src/assets/search.svg
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/Navigator.tsx
  frontend/src/components/ui/Navigator/Navigator.stories.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/Navigator/index.ts
  frontend/src/components/ui/SearchResult/index.ts
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationSearchBar/index.ts
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/stores/navItemsOpenStore.ts
  frontend/src/style/index.ts
Labels: 리팩터링, 기능추가, FE

#237 fix: 플렉스 박스 `align-items`가 동작하지 않는 에러를 개선한다
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
Labels: 버그, FE

#241 feat: Alert 컴포넌트를 구현한다
  frontend/src/components/common/Alert/Alert.stories.tsx
  frontend/src/components/common/Alert/Alert.tsx
  frontend/src/components/common/Alert/index.ts
Labels: 기능추가, FE, UI, 긴급

#244 chore: 스토리북에 msw을 적용한다
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: 기능추가, FE

#245 feat: 충전소 상세 정보 조회기능을 개선하고, 누적 고장 신고 확인 기능을 구현한다
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerCard.stories.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerCard.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.stories.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStationInfo.tsx
  frontend/src/components/ui/DetailedStationInfo/index.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data.ts
  frontend/src/types/index.ts
  frontend/src/utils/getObjectKeysType.ts
Labels: 기능추가, FE, UI

#250 refactor: 지도 api key 검사기능을 개선한다
  frontend/public/index.html
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/constants/index.ts
Labels: 리팩터링, 기능추가, FE, 긴급

#251 feat: 검색어 입력시 쿼리를 보내는 기능을 구현한다
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/jest.config.json
  frontend/src/assets/logo-icon.svg
  frontend/src/components/common/List/List.stories.tsx
  frontend/src/components/ui/BriefStationInfo.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerCard.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.tsx
  frontend/src/components/ui/Svg/LogoIcon.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useSearchedStations.ts
  frontend/src/hooks/useSelectedStation.ts
  frontend/src/hooks/useStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/searchWordStore.ts
  frontend/src/style/index.ts
  frontend/src/types/index.ts
  frontend/src/utils/getObjectKeysType.ts
  frontend/src/utils/getTypedObjectFromEntries.ts
  frontend/src/utils/getTypedObjectKeys.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 기능추가, FE

#232 refactor: 누적 혼잡도 시각화 컴포넌트의 재사용성을 높인다
  frontend/src/assets/logo-icon.svg
  frontend/src/components/ui/Graph/Bar.tsx
  frontend/src/components/ui/Graph/BarContainer.tsx
  frontend/src/components/ui/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/Graph/DayMenus.tsx
  frontend/src/components/ui/Graph/index.tsx
  frontend/src/components/ui/StatisticsGraph/DaySelectButton.tsx
  frontend/src/components/ui/StatisticsGraph/GraphBar.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.tsx
  frontend/src/components/ui/StatisticsGraph/index.ts
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/data.ts
Labels: 리팩터링, FE

#218 feat: 서버에서 충전소 정보들을 필터링 하는 기능을 만든다
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatus.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Coordinate.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Station.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/StationRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Stations.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/FakeStationRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/StationsTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/charger/ChargerFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/station/StationFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationServiceTest.java
Labels: 기능추가, BE

#235 feat: 충전소의 잘못된 정보를 제보하는 기능을 구현한다
  backend/src/docs/asciidoc/report.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/ReportController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationDetailReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationReportRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/report/ReportService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/report/dto/MisinformationReportRequest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/report/FakeMisinformationRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/report/MisinformationReportRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/report/ReportServiceTest.java
Labels: 기능추가, BE

#204 feat: 충전소 상세 조회 시 신고 횟수도 반환하도록 추가한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Station.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/StationRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
Labels: 기능추가, BE

#249 refactor: 혼잡도를 저장하는 기능을 개선한다
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatus.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatusCustomRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestionCustomRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerStatusCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/PeriodicCongestionCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/StationRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/service/charger/ChargerStateUpdateService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationServiceTest.java
Labels: 리팩터링, BE
