Repository woowacourse-teams/2023-car-ffeine, pull requests merged in 2023-08, with the labels that each got.

#258 feat: 충전기 고장 신고 기능을 구현한다
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerReportConfirmation.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStationInfo.tsx
  frontend/src/components/ui/ModalContainer.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useStationChargerReport.ts
  frontend/src/hooks/useUpdateStationChargerReport.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/modalStore.ts
  frontend/src/utils/configureToken.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 버그, 리팩터링, 기능추가, FE

#262 refactor: 충전소 리스트 UI, 필터링 UI를 개선한다
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationCard.stories.tsx
  frontend/src/components/ui/StationList/StationCard.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/mocks/data.ts
Labels: 리팩터링, FE, UI

#254 feat: 검색을 하는 기능을 구현한다
  .gitignore
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/StationRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/StationSearchResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/StationsSearchResponse.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/FakeStationRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/StationRepositoryTest.java
Labels: 기능추가, BE

#269 DB 접속이 안되는 오류를 해결한다
  backend/src/main/resources/application-dev.yml
Labels: 버그, BE

#271 API 명세와 다른 부분을 수정한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/ChargerSpecificResponse.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
Labels: 버그, BE

#270 fix: heap memory를 설정한다
  backend/Dockerfile
Labels: 버그, BE, 긴급

#216 feat: 토큰 생성 및 검증 기능을 구현한다
  backend/build.gradle
  backend/src/main/java/com/carffeine/carffeine/config/WebConfig.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/auth/MemberController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/auth/dto/JwtResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/auth/dto/MemberResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/filter/AuthenticateMember.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/Jwt.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/member/Member.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/member/MemberRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/AuthorizationException.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMember.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
  backend/src/main/java/com/carffeine/carffeine/station/service/auth/MemberService.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/station/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/congestion/CongestionControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/resources/application.yml
Labels: 기능추가, BE

#261 feat: Spring actuator 를 설정한다
  backend/build.gradle
  backend/src/main/resources/application.yml
Labels: 기능추가, BE

#273 refactor: 패키지 구조를 변경한다
  backend/src/main/java/com/carffeine/carffeine/config/WebConfig.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/AuthFilter.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/AuthMember.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/AuthMemberResolver.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/dto/AuthenticateMember.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/dto/JwtResponse.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/dto/MemberResponse.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/MemberRepository.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/TokenProvider.java
  backend/src/main/java/com/carffeine/carffeine/member/exception/MemberException.java
  backend/src/main/java/com/carffeine/carffeine/member/infrastructure/JWTProvider.java
  backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/auth/dto/JwtResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/auth/dto/MemberResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/AuthorizationException.java
  backend/src/test/java/com/carffeine/carffeine/station/MockBeanInjection.java
Labels: 리팩터링, BE

#276 refactor: 환경변수로 데이터베이스 정보 받도록 변경
  .github/workflows/backend-deploy.yml
  backend/src/main/resources/application-dev.yml
Labels: 리팩터링, BE

#279 feat: cors 와 timezone 을 설정한다
  backend/src/main/java/com/carffeine/carffeine/CarffeineApplication.java
  backend/src/main/java/com/carffeine/carffeine/config/WebConfig.java
  backend/src/main/java/com/carffeine/carffeine/web/CorsFilter.java
Labels: BE

#281 feat: 충전소 정보 수정 제안 기능을 구현한다
  frontend/src/components/common/TextField/TextField.stories.tsx
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.tsx
  frontend/src/components/ui/DetailedStationInfo/StationInformation.tsx
  frontend/src/components/ui/DetailedStationInfo/StationReportConfirmation.tsx
  frontend/src/hooks/useUpdateStationReport.ts
  frontend/src/mocks/handlers.ts
Labels: 기능추가, FE, UI

#280 feat: 아코디언 컴포넌트를 개발한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/Accordion/Accordion.stories.tsx
  frontend/src/components/ui/Accordion/BasePanel.tsx
  frontend/src/components/ui/Accordion/LastPanel.tsx
  frontend/src/components/ui/Accordion/Navigator.tsx
  frontend/src/components/ui/Accordion/hooks/useAccordionAction.ts
  frontend/src/components/ui/Accordion/index.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStationInfo.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/style/index.ts
Labels: 기능추가, FE, UI

#285 fix: 충돌 해결한다
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
Labels: 버그, FE, 긴급

#286 fix: 지도 이동 시 중복으로 데이터를 요청하는 문제 수정
  frontend/src/hooks/useUpdateStations.ts
Labels: 버그, FE, 긴급

#291 fix: 데이터 받아오는 부분 api 명세대로 변경한다
  frontend/src/hooks/useSearchedStations.ts
  frontend/src/mocks/handlers.ts
  frontend/src/types/index.ts
Labels: 버그, FE, 긴급

#296 메서드 잘못 호출한 부분을 수정한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/ReportController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/FaultReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationReport.java
  backend/src/main/java/com/carffeine/carffeine/station/service/report/dto/MisinformationReportRequest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
Labels: 버그, BE

#289 feat: 기본 페이지를 1로 선택해서 검색
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
Labels: BE, 긴급

#287 fix: 커넥션 풀 사이즈를 22개로 늘린다
  backend/src/main/resources/application.yml
Labels: 버그, BE, 긴급

#298 github action에 브랜치 수정
  .github/workflows/backend-deploy.yml
Labels: 버그, BE

#304 refactor: 실제 url에 연결하고 development 모드에서 서버를 유동적으로 선택할 수 있도록 개선한다
  frontend/src/components/ui/Accordion/Navigator.tsx
  frontend/src/components/ui/DevelopmentServerControlButton.tsx
  frontend/src/components/ui/DevelopmentServerSelect.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useSearchedStations.ts
  frontend/src/hooks/useSelectedStation.ts
  frontend/src/hooks/useStationChargerReport.ts
  frontend/src/hooks/useStations.ts
  frontend/src/hooks/useUpdateStationChargerReport.ts
  frontend/src/hooks/useUpdateStationReport.ts
  frontend/src/hooks/useUpdateStations.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/serverStore.ts
Labels: 리팩터링, 기능추가, FE

#308 fix: useUpdateStations의 기본 Fn 버그 수정
  frontend/src/hooks/useUpdateStations.ts
Labels: 버그, FE, 긴급

#310 feat: 검색시 limit 을 기본값 12개로 변경하고, 클라이언트가 수정할 수 있도록 변경한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
Labels: 기능추가, BE

#322 feat: 개선된 버튼 컴포넌트 구현한다
  frontend/src/components/common/Alert/Alert.tsx
  frontend/src/components/common/ButtonNext/ButtonNext.stories.tsx
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/common/ButtonNext/index.ts
  frontend/src/components/ui/MapController.tsx
  frontend/src/constants/styles.ts
  frontend/src/hooks/useStations.ts
  frontend/src/types/style.ts
Labels: 리팩터링, 기능추가, FE, UI

#323 feat: 디바운스 이용해 검색 기능 최적화한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/Accordion/index.tsx
  frontend/src/components/ui/ChargingSpeedIcon.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationListWindow.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/hooks/useDebounce.ts
  frontend/src/hooks/useUpdateSearchResult.ts
Labels: 리팩터링, 기능추가, FE

#329 fix: 변경된 db 접속 주소를 적용한다
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 리팩터링, BE, 페어

#330 fix: 초기 충전소 정보가 없어 발생하는 런타임 에러 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/Graph/BarContainer.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/useStationChargerReport.ts
  frontend/src/hooks/useUpdateStations.ts
Labels: 버그, FE, 긴급, 페어

#334 feat: 스케줄링을 profile에 따라 분리한다
  backend/src/main/java/com/carffeine/carffeine/config/SchedulingConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: 기능추가, BE

#336 refactor: 기존 Button 컴포넌트를 ButtonNext로 교체한다
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerReportConfirmation.tsx
  frontend/src/components/ui/DetailedStationInfo/CongestionStatistics.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.tsx
  frontend/src/components/ui/DetailedStationInfo/StationReportConfirmation.tsx
  frontend/src/components/ui/DevelopmentServerControlButton.tsx
  frontend/src/components/ui/DevelopmentServerSelect.tsx
  frontend/src/components/ui/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
Labels: 리팩터링, FE, UI

#341 fix: 혼잡도응답 dto 순서 수정한다
  backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
Labels: 버그, BE, 긴급

#342 fix: 키값 참조가 잘못 되어 발생하던 런타임 에러 수정
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo/CongestionStatistics.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/useStationCongestionStatistics.ts
  frontend/src/mocks/data.ts
  frontend/src/types/index.ts
Labels: 버그, FE, 긴급

#344 refactor: 기존의 google.maps.Marker를 google.maps.marker.AdvancedMarkerElement으로 교체한다
  frontend/src/App.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/index.tsx
  frontend/src/mocks/configureMsw.ts
  frontend/src/stores/googleMapStore.ts
  frontend/src/stores/markerInstanceStore.ts
  frontend/src/stores/mswModeStore.ts
Labels: 리팩터링, FE, UI

#346 refactor: api key 검사기 제거
  frontend/public/index.html
  frontend/src/index.tsx
Labels: 리팩터링, FE, 긴급

#348 refactor: .env으로 google maps api key을 설정한다
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-dev-deploy.yml
Labels: 리팩터링, FE, 긴급

#350 fix: webpack production mode build 오류를 수정한다
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-dev-deploy.yml
  frontend/webpack.config.js
Labels: 버그, FE, 긴급

#353 refactor: 좌측 메뉴에 의해 마커가 가려지는 문제를 해결한다
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/Accordion/hooks/useAccordionAction.ts
  frontend/src/components/ui/Accordion/index.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/hooks/useCalculatedMapDelta.ts
  frontend/src/hooks/useGoogleMap.tsx
  frontend/src/hooks/useStationSummary.tsx
  frontend/src/hooks/useStations.ts
  frontend/src/stores/componentWidthStore.ts
Labels: 버그, 리팩터링, FE

#359 fix: 상세정보가 없을 때도 상세정보창이 남아있는 오류 수정
  frontend/src/components/ui/DetailedStationInfo/DetailedStationInfo.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/hooks/useSelectedStation.ts
  frontend/src/hooks/useStationCongestionStatistics.ts
Labels: 버그, FE, 긴급

#362 refactor: 폴더 구조와 파일 이름을 개선한다
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerCard.tsx
  frontend/src/components/ui/DetailedStationInfo/ChargerReportConfirmation.tsx
  frontend/src/components/ui/DetailedStationInfo/CongestionStatistics.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStation.tsx
  frontend/src/components/ui/DetailedStationInfo/DetailedStationInfo.tsx
  frontend/src/components/ui/DetailedStationInfo/StationReportConfirmation.tsx
  frontend/src/components/ui/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/Graph/index.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/constants/chargers.ts
  frontend/src/constants/congestion.ts
  frontend/src/constants/errorMessages.ts
  frontend/src/constants/googleMaps.ts
  frontend/src/constants/index.ts
  frontend/src/constants/stationSearch.ts
  frontend/src/constants/storageKeys.ts
  frontend/src/constants/styles.ts
  frontend/src/hooks/google-maps/useCalculatedMapDelta.ts
  frontend/src/hooks/google-maps/useCurrentPosition.ts
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/hooks/useChangeStationDetails.ts
  frontend/src/hooks/useServerStationFilters.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/googleMapStore.ts
  frontend/src/stores/selectedServerStationFiltersStore.ts
  frontend/src/style/index.ts
  frontend/src/types/chargers.ts
  frontend/src/types/congestion.ts
  frontend/src/types/index.ts
  frontend/src/utils/configureToken.ts
Labels: 리팩터링, FE

#364 feat: 충전소 정보 수정 제안 시 단순 제보 기능을 구현한다
  frontend/src/components/ui/DetailedStationInfo/index.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/StationDetailsWindow/ChargerCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationDetailsWindow/StationInformation.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/index.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/ChargerReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportPreConfirmation.tsx
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
Labels: 리팩터링, 기능추가, FE, UI

#372 chore: prettier 3.0 버전으로 올리고 type 절대 경로를 추가한다
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/package.json
  frontend/src/components/common/Alert/Alert.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/google-maps/marker/StationMarker.tsx
  frontend/src/components/ui/BriefStationInfo.tsx
  frontend/src/components/ui/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/Graph/index.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationDetailsWindow/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationInformation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportPreConfirmation.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/style/index.ts
  frontend/src/utils/external-state/index.ts
  frontend/src/utils/getTypedObjectFromEntries.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 리팩터링, FE

#368 refactor: 충전소 신고 요청시 혼잡도 그래프가 새로고침 되는 문제를 개선한다
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
Labels: 버그, 리팩터링, FE

#373 feat: 스켈레톤을 구현한다
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/common/Skeleton/index.ts
Labels: 기능추가, FE, UI

#358 feat: docker 시작 전에 종료된 컨테이너를 제거한다
  .github/workflows/backend-deploy.yml
  .github/workflows/backend-dev-deploy.yml
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-dev-deploy.yml
Labels: BE, FE, 긴급

#383 refactor: context-path를 설정함으로 '/api'를 작성하지 않아도 prefix로 고정되도록 변경
  backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/congestion/CongestionController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/report/ReportController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/station/controller/congestion/CongestionControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/report/ReportControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/station/StationIntegrationTestFixture.java
Labels: 리팩터링, BE

#387 refactor: 폴더 구조와 파일 이름을 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/Accordion/hooks/useAccordionAction.ts
  frontend/src/components/ui/Accordion/index.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DevelopmentServerControlButton.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ModalContainer.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/ChargerReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportPreConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/domain.ts
  frontend/src/components/ui/StationDetailsWindow/reports/stationReportConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/stationReportConfirmation.test.ts
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSummaryWindow.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/google-maps/useCalculatedMapDelta.ts
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/hooks/useServerStationFilters.ts
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/briefStationInfoWindowStore.ts
  frontend/src/stores/config/mswModeStore.ts
  frontend/src/stores/config/serverStore.ts
  frontend/src/stores/google-maps/googleMapStore.ts
  frontend/src/stores/google-maps/markerInstanceStore.ts
  frontend/src/stores/google-maps/stationSummaryWindowStore.ts
  frontend/src/stores/layout/componentWidthStore.ts
  frontend/src/stores/layout/forceOpenAccordionPanelStore.ts
  frontend/src/stores/layout/modalStore.ts
  frontend/src/stores/navItemsOpenStore.ts
  frontend/src/stores/selectedStationStore.ts
  frontend/src/stores/station-filters/clientStationFiltersStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/types/chargers.ts
  frontend/src/types/congestion.ts
  frontend/src/types/index.ts
  frontend/src/types/stations.ts
Labels: 리팩터링, FE, 페어

#392 fix: enum 컨버터로 매핑되지 않는 에러를 해결한다
  backend/src/main/java/com/carffeine/carffeine/station/config/RequestPeriodConverter.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
Labels: 버그, BE, 긴급

#394 refactor: 아코디언 컴포넌트를 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/Accordion/Accordion.stories.tsx
  frontend/src/components/ui/Accordion/BasePanel.tsx
  frontend/src/components/ui/Accordion/LastPanel.tsx
  frontend/src/components/ui/Accordion/hooks/useAccordionAction.ts
  frontend/src/components/ui/Accordion/index.tsx
  frontend/src/components/ui/NavigationBar/NavigationBar.tsx
  frontend/src/components/ui/NavigationBar/index.ts
  frontend/src/components/ui/Navigator/Navigator.stories.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/Navigator/index.ts
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSummaryWindow.tsx
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/src/components/ui/compound/Graph/BarContainer.tsx
  frontend/src/components/ui/compound/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/compound/Graph/DayMenus.tsx
  frontend/src/components/ui/compound/Graph/index.tsx
  frontend/src/components/ui/compound/NavigationBar/BasePanel.tsx
  frontend/src/components/ui/compound/NavigationBar/CloseButton.tsx
  frontend/src/components/ui/compound/NavigationBar/LastPanel.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/ui/compound/NavigationBar/hooks/useNavigationBar.ts
  frontend/src/components/ui/compound/NavigationBar/index.tsx
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/stores/layout/forceOpenAccordionPanelStore.ts
  frontend/src/stores/layout/navigationBarPanelStore.tsx
Labels: 리팩터링, FE

#393 refactor: 충전소 정보 제안 관련 기능을 개선한다
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/StationReportPreConfirmation.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
Labels: 버그, 리팩터링, 기능추가, FE

#374 refactor: 생성일과 수정일을 추가한다.
  backend/src/main/java/com/carffeine/carffeine/CarffeineApplication.java
  backend/src/main/java/com/carffeine/carffeine/common/domain/BaseEntity.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatus.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/FaultReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationDetailReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/report/MisinformationReport.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Station.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerStatusCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/PeriodicCongestionCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/StationRepositoryImpl.java
  backend/src/test/java/com/carffeine/carffeine/station/MockBeanInjection.java
Labels: 리팩터링, BE

#396 feat: 로딩 스켈레톤 컴포넌트를 충전소 조회에 적용한다
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/ui/StationDetailsWindow/ChargerCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsViewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationDetailsWindow/StationInformation.tsx
  frontend/src/components/ui/StationDetailsWindow/StationInformationSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatisticsSkeleton.tsx
  frontend/src/components/ui/StationList/EmptyStationsNotice.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationSummaryCardSkeleton.stories.tsx
  frontend/src/components/ui/StationList/StationSummaryCardSkeleton.tsx
Labels: 리팩터링, 기능추가, FE, UI

#403 fix: 클라이언트 빌드 버그를 수정한다.
  frontend/package.json
  frontend/yarn.lock
Labels: 버그, FE, 긴급

#409 feat: 토스트 컴포넌트를 구현한다
  frontend/.prettierrc
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/index.ts
  frontend/src/constants/errorMessages.ts
  frontend/src/stores/layout/toastStore.ts
  frontend/src/style/index.ts
  frontend/src/types/style.ts
  frontend/src/utils/calculateToastDuration.ts
Labels: 기능추가, FE

#411 feat: 별점 컴포넌트를 구현한다
  frontend/src/components/ui/Star/Star.stories.tsx
  frontend/src/components/ui/Star/Star.tsx
  frontend/src/components/ui/Star/index.ts
  frontend/src/components/ui/StarRatings/StarRatings.stories.tsx
  frontend/src/components/ui/StarRatings/StarRatings.tsx
  frontend/src/components/ui/StarRatings/index.tsx
Labels: 기능추가, FE, UI

#413 feat: 토스트 여러 개 나오는 기능 구현한다
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/ToastContainer.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/stores/layout/toastStore.ts
  frontend/src/stores/layout/toastStore.tsx
  frontend/src/style/index.ts
Labels: 기능추가, FE

#420 feat: 간편 로그인 기능을 구현한다
  frontend/package.json
  frontend/src/assets/google-login-button.svg
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/LoginModal/LoginModal.stories.tsx
  frontend/src/components/ui/LoginModal/LoginModal.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/storageKeys.ts
  frontend/src/index.tsx
  frontend/src/router/index.tsx
  frontend/src/types/login.ts
  frontend/src/utils/login/index.ts
  frontend/yarn.lock
Labels: 기능추가, FE, UI

#423 feat: 개인화 메뉴 관련 mock api를 추가한다
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/types/login.ts
  frontend/src/utils/getTypedObjectEntries.ts
Labels: 기능추가, FE

#426 refactor: 구현된 필터링 컴포넌트에 변경된 api를 적용한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useUserFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/hooks/useServerStationFilterActions.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/webpack.config.js
Labels: 리팩터링, FE

#432 feat: 충전소 리뷰 조회 기능을 구현한다
  frontend/src/components/ui/StationDetailsWindow/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCardsLoading.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewPreviewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/UserRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/UserRatings.tsx
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviewRatings.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviews.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/types/stations.ts
  frontend/src/utils/configureToken.ts
  frontend/src/utils/index.ts
  frontend/src/utils/randomDataGenerator.ts
Labels: 기능추가, FE, UI

#434 refactor: 구글 지도를 전반적으로 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.ts
  frontend/src/mocks/data.ts
  frontend/src/stores/google-maps/googleMapStore.ts
  frontend/src/stores/google-maps/stationSummaryWindowStore.ts
  frontend/src/style/GlobalStyle.ts
  frontend/src/utils/google-maps/index.ts
Labels: 리팩터링, FE

#440 feat: 로그아웃 기능을 구현한다
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/LoginModal/LoginModal.stories.tsx
  frontend/src/components/ui/LoginModal/LoginModal.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/NavigationBar/loginMenus.tsx
  frontend/src/components/ui/compound/PopupMenu/Menus.tsx
  frontend/src/components/ui/compound/PopupMenu/PopupMenu.stories.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/hooks/tanstack-query/station-filters/useUserFilters.ts
  frontend/src/stores/userTokenStore.ts
  frontend/src/utils/login/index.ts
Labels: 기능추가, FE, UI

#445 fix: 충전소 검색기를 통해 이동 시, 줌 조절이 안되고 InfoWindow가 동작하지 않는 문제를 수정한다
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResultSkeleton.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/google-maps/useGoogleMap.tsx
Labels: 버그, 리팩터링, FE, UI

#449 fix: 스토리북 빌드 오류 수정
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/index.ts
Labels: 버그, FE, 긴급

#451 feat: 필터 API를 구현한다
  backend/src/docs/asciidoc/Filter.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/carffeine/carffeine/filter/controller/FilterController.java
  backend/src/main/java/com/carffeine/carffeine/filter/controller/dto/FiltersResponse.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/Filter.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/FilterRepository.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/FilterType.java
  backend/src/main/java/com/carffeine/carffeine/filter/exception/FilterException.java
  backend/src/main/java/com/carffeine/carffeine/filter/exception/FilterExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/filter/service/FilterService.java
  backend/src/main/java/com/carffeine/carffeine/filter/service/dto/FilterRequest.java
  backend/src/main/java/com/carffeine/carffeine/filter/service/dto/FiltersRequest.java
  backend/src/test/java/com/carffeine/carffeine/filter/controller/FilterControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/domain/FilterRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/domain/FilterTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/fake/FakeFilterRepository.java
  backend/src/test/java/com/carffeine/carffeine/filter/integration/FilterIntegrationFixture.java
  backend/src/test/java/com/carffeine/carffeine/filter/integration/FilterIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/service/FilterServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
Labels: 기능추가, BE

#454 feat: 로그인, 유저 정보 조회 mock api를 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useUserFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.tsx
  frontend/src/hooks/useServerStationFilterActions.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/login/loginHandlers.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/mocks/handlers/station-filters/serverFilterHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/stores/layout/navigationBarPanelStore.tsx
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/utils/google-maps/index.ts
  frontend/src/utils/login/index.ts
Labels: 기능추가, FE

#453 feat: 유저가 선호하는 필터를 저장하는 기능을 구현한다
  backend/src/docs/asciidoc/filter.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/carffeine/carffeine/filter/controller/dto/FiltersResponse.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/Filter.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/MemberFilter.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/MemberFilterRepository.java
  backend/src/main/java/com/carffeine/carffeine/member/exception/MemberExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/Charger.java
  backend/src/test/java/com/carffeine/carffeine/filter/fake/FakeFilterRepository.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/member/controller/MemberControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/member/domain/FakeMemberFilterRepository.java
  backend/src/test/java/com/carffeine/carffeine/member/domain/MemberFilterRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/member/integration/MemberFilterIntegrationFixture.java
  backend/src/test/java/com/carffeine/carffeine/member/integration/MemberFilterIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/member/service/MemberServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/FakeStationRepository.java
Labels: 기능추가, BE

#456 refactor: 로그인, 유저 정보 조회 기능을 수정한다
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/utils/login/index.ts
Labels: 리팩터링, FE

#457 refactor: 변경된 api 명세에 맞게 구현한 개인화 메뉴 관련 mock api들을 수정한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationDetailsWindow/ChargerCard.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/constants/chargers.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/storageKeys.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useUserFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.ts
  frontend/src/hooks/useServerStationFilterActions.ts
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/mocks/handlers/station-filters/serverFilterHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/stores/login/memberInfoStore.ts
  frontend/src/stores/login/memberTokenStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/stores/userTokenStore.ts
  frontend/src/types/chargers.ts
  frontend/src/types/serverStationFilter.ts
  frontend/src/types/stations.ts
  frontend/src/utils/login/index.ts
Labels: 리팩터링, FE

#450 feat: 리뷰 댓글 CRUD 기능을 구현한다
  backend/src/docs/asciidoc/review.adoc
  backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthFilter.java
  backend/src/main/java/com/carffeine/carffeine/auth/domain/TokenProvider.java
  backend/src/main/java/com/carffeine/carffeine/auth/exception/AuthExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/JwtProvider.java
  backend/src/main/java/com/carffeine/carffeine/common/domain/BaseEntity.java
  backend/src/main/java/com/carffeine/carffeine/config/WebConfig.java
  backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewException.java
  backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/dto/CreateReviewRequest.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/helper/integration/AcceptanceTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/member/fixture/MemberFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReviewRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/StationRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReviewFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
Labels: 기능추가, BE

#459 feat: 충전소 후기의 등록/수정/삭제 기능을 구현한다
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/systems.ts
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ModalContainer.tsx
  frontend/src/components/ui/ModalSecondaryContainer.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsViewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportPreConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/domain.ts
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.test.ts
  frontend/src/components/ui/StationDetailsWindow/reviews/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ContentField.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/HeaderWithRating.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ReviewCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ReviewModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformation.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformationSkeleton.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviews.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
  frontend/src/stores/layout/modalSecondaryStore.ts
Labels: 리팩터링, 기능추가, FE, UI

#465 Skeleton을 감싸고 있는 불필요한 spacing용 Box 제거한다
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsViewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformationSkeleton.tsx
  frontend/src/components/ui/StationList/StationSummaryCardSkeleton.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResultSkeleton.tsx
Labels: 리팩터링, FE, UI

#468 feat: 차량 선택 관련 mock api와 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/index.ts
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.stories.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.stories.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/tanstack-query/car/useCars.ts
  frontend/src/hooks/tanstack-query/station-filters/useCarFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useUpdateStations.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/car/carHandler.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/stores/login/memberInfoStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/types/cars.ts
  frontend/src/utils/login/index.ts
Labels: 리팩터링, 기능추가, FE, UI

#469 평균 별점 API 수정을 대응한다
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatingsSkeleton.tsx
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviewRatings.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
  frontend/src/types/stations.ts
Labels: 버그, 리팩터링, FE

#473 충전소 후기 답글의 등록/수정/삭제 기능을 구현한다
  frontend/src/components/ui/StationDetailsWindow/reviews/ReviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/cards/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/cards/ReviewCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/cards/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/cards/ReviewCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/cards/ReviewCardsLoading.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ReplyCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ReplyModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/crud/ReviewModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewSkeleton.tsx
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReply.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
Labels: 기능추가, FE, UI

#477 회의 중 결정된 사안을 반영한다
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/SelectBox/SelectBox.stories.tsx
  frontend/src/components/common/SelectBox/SelectBox.tsx
  frontend/src/components/common/SelectBox/index.ts
Labels: 리팩터링, 기능추가, FE, UI

#471 refactor: 유저 필터링 정보 등록 API 명세 변경을 적용한다
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/index.tsx
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/utils/login/index.ts
Labels: 리팩터링, FE

#481 design: 충전소 마커를 디자인한다
  frontend/src/assets/blue-marker.svg
  frontend/src/components/ui/CarFfeineMarker/CarFfeine.stories.tsx
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/CarFfeineMarker/index.ts
  frontend/src/hooks/google-maps/useGoogleMap.tsx
Labels: FE, UI

#488 design: 충전소 검색창 디자인 개선 및 라벨 문구 변경한다
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/components/ui/StationList/StationSummaryCardSkeleton.tsx
  frontend/src/components/ui/StationSummaryWindow.tsx
Labels: FE, UI

#492 refactor: MemberCar 찾지를 못하면 null을 반환한다
  backend/src/main/java/com/carffeine/carffeine/member/exception/MemberExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
Labels: 리팩터링, BE

#493 feat: 통합 별점 조회 기능 구현
  backend/src/docs/asciidoc/review.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/TotalRatingsResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReviewRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
Labels: 기능추가, BE

#494 design: 상세정보 페이지를 개선한다
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatisticsSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportPreConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreviewSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatingsSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCardSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCreateButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewModifyButton.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformation.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/src/components/ui/compound/Graph/DayMenus.tsx
  frontend/src/components/ui/compound/Graph/index.tsx
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/mocks/handlers/station-details/reports/stationReportHandlers.ts
  frontend/src/style/index.ts
Labels: 리팩터링, FE, UI

#497 새로운 충전소 후기/답글 api 명세에 대응한다
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyModify.tsx
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReply.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
Labels: 리팩터링, FE

#502 충전소 검색창의 UX를 개선한다
  frontend/src/components/common/Loader/Loader.stories.tsx
  frontend/src/components/common/Loader/Loader.tsx
  frontend/src/components/common/Loader/index.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
Labels: 리팩터링, 기능추가, FE, UI

#505 서버 필터링 스켈레톤 컴포넌트 구현한다
  frontend/src/components/ui/ServerStationFilters/FilterOptionSkeleton.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFiltersSkeleton.tsx
Labels: 리팩터링, FE, UI

#496 refactor: MemberCar에서 Car가 없다면 null값을 주도록 변경
  backend/src/main/java/com/carffeine/carffeine/member/controller/dto/MemberCarInfoResponse.java
  backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
Labels: 리팩터링, BE

#508 refactor: 리뷰의 평균 별점을 가져올 때 발생하는 에러를 해결한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReviewRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
Labels: 버그, BE

#510 PR시 프론트엔드 테스트 자동화 기능 추가
  .github/workflows/frontend-test-when-pr.yml
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.test.ts
Labels: 리팩터링, FE, 긴급

#511 fix: 필터링 적용이 안되는 오류를 수정한다
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/constants/storageKeys.ts
  frontend/src/hooks/tanstack-query/station-filters/useCarFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/index.tsx
  frontend/src/stores/config/mswModeStore.ts
  frontend/src/stores/config/serverStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/utils/login/index.ts
  frontend/src/utils/request-query-params/index.ts
Labels: 버그, FE, 긴급

#516 충전소 상세정보의 테스트 케이스를 추가한다
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.test.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportConfirmation.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportPreConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.test.ts
  frontend/yarn.lock
Labels: 리팩터링, FE

#520 후기/답글 관련 로직을 개선한다
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewList.tsx
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReplies.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
Labels: 버그, 리팩터링, FE

#523 refactor: prometheus 설정 추가
  .github/workflows/backend-deploy.yml
  backend/src/main/resources/application.yml
Labels: 리팩터링, BE

#526 빌드 버그를 수정한다
  .github/workflows/frontend-test-when-pr.yml
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportPreConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.render.test.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 버그, FE, 긴급

#530 feat: 개발 서버도 모니터링 툴을 적용한다
  .github/workflows/backend-dev-deploy.yml
Labels: 기능추가, BE

#531 지도 요청을 디바운스로 처리하는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/utils/debounce.ts
Labels: 버그, 리팩터링, FE, 긴급

#533 refactor: 빌드 관련 설정을 개선한다
  .github/workflows/frontend-dev-deploy.yml
  frontend/.gitignore
  frontend/package.json
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/index.tsx
  frontend/src/router/index.tsx
  frontend/src/utils/login/index.ts
  frontend/tsconfig.json
  frontend/webpack.config.dev.js
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 리팩터링, FE

#534 충전소 상세 정보 디자인을 개선한다
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/components/ui/StationList/StationListWindow.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
Labels: 리팩터링, 기능추가, FE

#536 refactor: 차량 필터링 관련 기능 명세 변경을 적용한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/index.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/components/ui/modal/CarModal/fetch/index.ts
  frontend/src/hooks/tanstack-query/car/useCars.ts
  frontend/src/hooks/tanstack-query/station-filters/useCarFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/index.tsx
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/car/carHandler.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/stores/login/memberInfoStore.ts
  frontend/src/stores/login/memberTokenStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
Labels: 버그, 리팩터링, FE

#539 fix: 로그인 오류 수정
  frontend/src/utils/login/index.ts
Labels: 버그, FE, 긴급

#542 fix: 잘못된 경로로 요청을 발생시키는 오류 수정
  frontend/src/stores/config/serverStore.ts
  frontend/src/utils/login/index.ts
Labels: 버그, FE, 긴급

#545 fix: 상세 정보 페이지의 버그를 수정한다
  frontend/src/components/ui/StationDetailsWindow/reports/charger/ChargerReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportButton.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyModify.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCreate.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewModifyButton.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReplies.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviews.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
Labels: 버그, 리팩터링, FE

#554 feat: 토큰 만료 후 인증이 필요한 서비스에 접근시 자동 로그아웃 되는 기능을 구현한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useServerStationFiltersComponentActions.ts
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/components/ui/modal/CarModal/fetch/index.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/useServerStationFilterActions.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/stores/login/memberInfoStore.ts
  frontend/src/stores/login/memberTokenStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/utils/fetch/index.ts
  frontend/src/utils/login/index.ts
Labels: 기능추가, FE

#555 refactor: 충전소 조회 원상복구
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationsSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/StationRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/FakeStationRepository.java
Labels: 리팩터링, BE

#560 fix: 필터링 적용하기 오류를 개선한다
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/yarn.lock
Labels: 버그, FE, 긴급

#558 fix: 경로 인식 못하는 부분 수정
  backend/src/docs/asciidoc/index.adoc
Labels: 버그, BE

#564 feat: 충전소 간단 정보 모달에 닫기 버튼 기능 추가한다
  frontend/src/components/ui/StationSummaryWindow.tsx
  frontend/src/style/GlobalStyle.ts
Labels: 기능추가, FE, UI

#567 refactor: 기준 줌 레벨을 화면 사이즈에 맞춰서 조절한다
  frontend/src/components/ui/StationDetailsWindow/reports/ReportButton.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/utils/google-maps/index.ts
Labels: 리팩터링, FE, 긴급

#569 refactor: 클라이언트 필터링 컴포넌트를 개선한다
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/components/ui/compound/NavigationBar/CloseButton.tsx
  frontend/src/components/ui/compound/NavigationBar/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/google-maps/useCalculatedMapDelta.ts
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/stores/layout/componentWidthStore.ts
  frontend/src/utils/google-maps/getCalculatedMapDelta.ts
Labels: 리팩터링, FE

#570 feat: 마커 로딩 스피너 구현한다
  frontend/src/components/common/Loader/Loader.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationMarkerLoadingSpinner.tsx
  frontend/src/utils/google-maps/getCalculatedMapDelta.ts
  frontend/webpack.config.prod.js
Labels: 기능추가, FE, UI

#565 fix: restdocs index.html 에서 안 보이는 문제 해결한다
  .github/workflows/backend-deploy.yml
  .github/workflows/backend-dev-deploy.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
Labels: 버그, BE

#571 refactor: 댓글 및 답글 삭제 기능을 추가한다
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReplyRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReplyService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReplyControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReplyRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReviewRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReplyRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReplyFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReviewFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReplyIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReplyIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReplyServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
Labels: 리팩터링, BE

#573 design: 로그인 모달 디자인을 개선한다
  frontend/src/assets/google-logo.svg
  frontend/src/components/common/Loading/Loading.tsx
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.tsx
  frontend/src/types/assets.d.ts
  frontend/webpack.config.dev.js
  frontend/webpack.config.prod.js
Labels: FE, UI

#576 fix: 잘못된 config 코드 수정한다
  frontend/webpack.config.dev.js
Labels: 버그, FE, 긴급

#575 design: 클라이언트 필터 디자인 개선한다
  frontend/src/components/ui/ClientStationFilters.tsx
Labels: 리팩터링, FE, UI

#579 refactor: 충전소 후기를 개선한다
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewList.tsx
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
Labels: 리팩터링, FE, UI

#580 refactor: ref 제거 및 css으로 툴팁 구현한다
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/PopupMenu/Menus.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/components/ui/modal/LoginModal/LoginModal.tsx
  frontend/yarn.lock
Labels: 리팩터링, FE

#582 design: 검색바와 클라이언트 필터링 위치 맞춘다
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
Labels: FE, UI

#585 feat: 반응형 NavigationBar 컴포넌트를 추가한다
  frontend/.gitignore
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/DevelopmentServerControlButton.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/NavigationBar/index.ts
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/Navigator/index.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFiltersSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationListWindow.tsx
  frontend/src/components/ui/StationMarkerLoadingSpinner.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/components/ui/compound/NavigationBar/BasePanel.tsx
  frontend/src/components/ui/compound/NavigationBar/CloseButton.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/PopupMenu/Menus.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/constants/index.ts
  frontend/src/style/mediaQuery.ts
Labels: 리팩터링, FE, UI

#591 refactor: 잘못된 필터링을 수정하고 불필요한 출력문을 제거한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformation.tsx
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
Labels: 🚑 버그, 🛠️ 리팩터링, FE, 🚨 긴급

#587 fix: 공공 데이터에서 받아온 시간과 조회하는 시간이 다른 문제를 해결한다
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerStatusCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/service/charger/dto/ChargerStateRequest.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/StationInfoRequest.java
Labels: 🚑 버그, BE

#594 refactor: 모바일에서 필터 적용하기 버튼이 보이지 않는 현상을 개선한다
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/compound/PopupMenu/Menus.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
Labels: FE, 🦜 UI

#596 refactor: 디자인을 일부 개선한다
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationListWindow.tsx
  frontend/src/components/ui/StationMarkerLoadingSpinner.tsx
Labels: 🚑 버그, FE, 🦜 UI, 🚨 긴급

#603 refactor: 빌드시 포함되는 필요없는 패키지들을 정리한다
  frontend/package.json
  frontend/src/index.prod.tsx
  frontend/src/index.tsx
  frontend/src/stores/config/mswModeStore.ts
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE

#607 feat: 구글 지도 랜드마크 클릭 못하게 하는 기능 추가한다
  frontend/src/stores/google-maps/googleMapStore.ts
Labels: 🌱 기능추가, FE

#611 refactor: 서버 선택 기능을 개선한다
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/DevelopmentServerControlButton.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useServerStationFiltersComponentActions.ts
  frontend/src/components/ui/modal/CarModal/fetch/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/server.ts
  frontend/src/hooks/tanstack-query/car/useCars.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReplies.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviewRatings.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviews.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-filters/useCarFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/mocks/handlers/car/carHandler.ts
  frontend/src/mocks/handlers/login/loginHandlers.ts
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/station-details/reports/stationReportHandlers.ts
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
  frontend/src/mocks/handlers/station-details/stationDetailHandlers.ts
  frontend/src/mocks/handlers/station-details/statisticsHandlers.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/mocks/handlers/station-filters/serverFilterHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/mocks/handlers/stationSearchHandlers.ts
  frontend/src/stores/config/mswModeStore.ts
  frontend/src/stores/config/serverStore.ts
  frontend/src/stores/config/serverUrlStore.ts
  frontend/src/utils/login/index.ts
Labels: 🛠️ 리팩터링, FE

#615 refactor: 차량 정보 필터링 반영 기능을 개선한다
  frontend/src/components/google-maps/map/ApiKeyChecker.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ServerStationFilters/FilterOption.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useStationFilters.ts
  frontend/src/components/ui/StationDetailsWindow/reports/ReportButton.tsx
  frontend/src/components/ui/StationMarkerLoadingSpinner.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/server.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-markers/useStations.ts
  frontend/src/hooks/useServerStationFilterActions.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/memberHandlers.ts
  frontend/src/mocks/handlers/station-filters/memberFilterHandlers.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/stores/login/memberInfoStore.ts
  frontend/src/stores/login/memberTokenStore.ts
  frontend/src/stores/station-filters/serverStationFiltersStore.ts
  frontend/src/utils/configureToken.ts
  frontend/src/utils/fetch/index.ts
  frontend/src/utils/google-maps/getCalculatedMapDelta.ts
  frontend/src/utils/login/index.ts
Labels: 🛠️ 리팩터링, FE

#632 fix: 프로덕션 빌드 오류 개선
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
Labels: 🚑 버그, FE, 🚨 긴급
