Repository woowacourse-teams/2023-car-ffeine, pull requests merged in 2023-11, with the labels that each got.

#921 refactor: 필요없는 코드 제거한다
  frontend/src/components/common/ListItem/ListItem.stories.tsx
  frontend/src/components/common/Tab/Menu.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarker.tsx
  frontend/src/components/ui/Navigator/NavigationBar/BasePanel.tsx
  frontend/src/components/ui/Navigator/NavigationBar/LastPanel.tsx
  frontend/src/components/ui/Navigator/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
Labels: 🛠️ 리팩터링, FE

#923 fix: 충전소 리스트에서 로딩을 보여주지 않아도 되는 상황에 보여지는 현상을 개선한다
  frontend/package-lock.json
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCardList.tsx
  frontend/yarn.lock
Labels: 🚑 버그, FE

#924 refactor: 마커 렌더링 방식을 개선한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/LargeDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/hooks/useRenderClusterMarker.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/components/RegionMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/MaxDeltaAreaMarkerContainer/hooks/useRenderRegionMarker.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/SmallMediumDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/SmallMediumDeltaAreaMarkerContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/LargeDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/components/ClusterMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/components/StyledClusterMarker.stories.tsx
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/components/StyledClusterMarker.tsx
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/hooks/useClusterMarkersQuery.ts
  frontend/src/components/google-maps/marker/components/LargeDeltaAreaMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/components/MarkerContainers/MarkerContainers.tsx
  frontend/src/components/google-maps/marker/components/MarkerContainers/index.ts
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/MaxDeltaAreaMarkerContainer.tsx
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/components/RegionMarker.stories.tsx
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/components/RegionMarker.tsx
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/components/RegionMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/hooks/useRegionMarkersQuery.ts
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/components/MaxDeltaAreaMarkerContainer/types/index.ts
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/SmallMediumDeltaAreaContainer.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeine.stories.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.style.ts
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.test.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/CarFfeineMarker/index.ts
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/marker/CarffeineMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/components/marker/DefaultMarkerRenderer.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/constants/index.ts
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/hooks/useStationMarkersQuery.ts
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/index.ts
  frontend/src/components/google-maps/marker/hooks/useMarker.tsx
  frontend/src/components/google-maps/marker/tools/index.ts
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/mocks/data/regions.ts
  frontend/src/mocks/handlers/station-markers/stationMarkerHandlers.ts
  frontend/src/tools/getChargerCountsAndAvailability.ts
Labels: 🛠️ 리팩터링, FE

#931 fix: 잘못된 import 경로로 인해 빌드가 되지 않는 문제를 수정한다
  frontend/src/components/google-maps/marker/components/MarkerContainers/MarkerContainers.tsx
  frontend/src/components/google-maps/marker/components/SmallMediumDeltaAreaMarkerContainer/SmallMediumDeltaAreaMarkerContainer.tsx
Labels: 🚑 버그, FE, 🚨 긴급
