Repository woowacourse-teams/2023-car-ffeine, pull requests merged in 2023-09, with the labels that each got.

#640 refactor: 혼잡도 그래프의 시멘틱 태그를 progress로 수정한다
  frontend/package-lock.json
  frontend/src/components/ui/compound/Graph/Bar.stories.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#641 refactor: 지도 확대 안내 토스트를 닫히지 않는 모달로 변경한다
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/WarningModal/ZoomWarningModal.tsx
  frontend/src/components/common/WarningModal/index.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/ModalContainer.tsx
  frontend/src/components/ui/ModalSecondaryContainer.tsx
  frontend/src/components/ui/WarningModalContainer.tsx
  frontend/src/stores/layout/modalSecondaryStore.ts
  frontend/src/stores/layout/warningModalStore.ts
Labels: 🛠️ 리팩터링, FE

#633 refactor: Car API 조회 기능을 Querydsl로 리팩토링 진행한다
  backend/src/docs/asciidoc/car.adoc
  backend/src/docs/asciidoc/filter.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/carffeine/carffeine/car/controller/CarController.java
  backend/src/main/java/com/carffeine/carffeine/car/controller/dto/MemberCarInfoResponse.java
  backend/src/main/java/com/carffeine/carffeine/car/domain/MemberCar.java
  backend/src/main/java/com/carffeine/carffeine/car/domain/MemberCarRepository.java
  backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/dto/CarResponse.java
  backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/dto/CarsResponse.java
  backend/src/main/java/com/carffeine/carffeine/car/service/CarQueryService.java
  backend/src/main/java/com/carffeine/carffeine/car/service/CarService.java
  backend/src/main/java/com/carffeine/carffeine/filter/controller/FilterController.java
  backend/src/main/java/com/carffeine/carffeine/filter/controller/dto/FiltersResponse.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/MemberFilter.java
  backend/src/main/java/com/carffeine/carffeine/filter/domain/MemberFilterRepository.java
  backend/src/main/java/com/carffeine/carffeine/filter/exception/FilterExceptionType.java
  backend/src/main/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/filter/infrastructure/repository/dto/FilterResponse.java
  backend/src/main/java/com/carffeine/carffeine/filter/service/FilterQueryService.java
  backend/src/main/java/com/carffeine/carffeine/filter/service/FilterService.java
  backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
  backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
  backend/src/test/java/com/carffeine/carffeine/car/controller/CarControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/car/fake/FakeMemberCarRepository.java
  backend/src/test/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/car/integration/CarIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/car/integration/MemberCarIntegrationFixture.java
  backend/src/test/java/com/carffeine/carffeine/car/integration/MemberCarIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/car/service/CarQueryServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/car/service/CarServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/controller/FilterControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/domain/MemberFilterRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/fake/FakeMemberFilterRepository.java
  backend/src/test/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/integration/MemberFilterIntegrationFixture.java
  backend/src/test/java/com/carffeine/carffeine/filter/integration/MemberFilterIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/service/FilterQueryServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/filter/service/FilterServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/member/controller/MemberControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/member/service/MemberServiceTest.java
Labels: 🛠️ 리팩터링, BE

#643 refactor: 웹 화면 확대 기능을 제거한다
  frontend/public/index.html
Labels: 🛠️ 리팩터링, FE

#644 refactor: 프론트엔드 배포 속도를 향상시킨다
  .github/workflows/frontend-deploy.yml
  .github/workflows/frontend-dev-deploy.yml
  frontend/DevDockerfile
  frontend/Dockerfile
Labels: 🛠️ 리팩터링, FE

#645 feat: 검색창을 닫아도 검색바는 지도 위에 보이도록 한다
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/WarningModalContainer.tsx
  frontend/src/hooks/useMediaQueries.ts
  frontend/src/stores/layout/navigationBarPanelStore.tsx
Labels: 🌱 기능추가, FE

#647 refactor: 충전소 조회를 Dto projection으로 변경한다
  backend/src/docs/asciidoc/station.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/ChargerSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationsSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/dto/StationsSummaryResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/charger/Charger.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Station.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/ChargerSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationInfo.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationSearchResult.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationSimpleResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationSpecificResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationSummaryResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/StationsSearchResponse.java
  backend/src/main/resources/db/migration/V8__add_ charger_index.sql
  backend/src/test/java/com/carffeine/carffeine/admin/service/AdminStationServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/StationRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/station/StationsTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/station/StationFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationRepositoryImplTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/station/StationIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/station/StationIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationQueryServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationServiceTest.java
Labels: 🛠️ 리팩터링, BE

#649 refactor: Periodic Request를 24시간 기준으로 추가
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/RequestPeriod.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/congestion/RequestPeriodTest.java
Labels: 🛠️ 리팩터링, BE

#656 feat: 새로운 충전소 조회 api 명세 적용한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/Marker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useStationFilters.ts
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSummaryWindow.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/modal/CarModal/CarModal.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/fetch/fetchStationSummaries.ts
  frontend/src/hooks/fetch/useFetchStationSummaries.ts
  frontend/src/hooks/fetch/useFetchStationSummary.ts
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationSummaries.ts
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/types/stations.ts
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE, 🫱🏻‍🫲🏻 페어

#658 fix: 명세 변경 적용
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
  frontend/src/mocks/handlers/station-markers/stationHandlers.ts
  frontend/src/types/stations.ts
Labels: 🚑 버그, FE, 🚨 긴급

#659 refactor: styled-components 의 props 경고를 제거한다
  frontend/src/components/common/Box/Box.stories.tsx
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/List/List.stories.tsx
  frontend/src/components/common/ListItem/ListItem.stories.tsx
  frontend/src/components/common/Loader/Loader.stories.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/TextField/TextField.stories.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/Star/Star.stories.tsx
  frontend/src/components/ui/StarRatings/StarRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.stories.tsx
  frontend/src/components/ui/StationList/StationSummaryCardSkeleton.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/compound/NavigationBar/NavigationBar.stories.tsx
Labels: 🚑 버그, 🛠️ 리팩터링, FE

#661 refactor: 혼잡도 관련 코드 리팩토링을 한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/congestion/CongestionController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestionCustomRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestionRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/PeriodicCongestionCustomRepositoryImpl.java
  backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/carffeine/carffeine/station/controller/congestion/CongestionControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/congestion/RequestPeriodTest.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/PeriodicCongestionCustomRepositoryImplTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/congestion/CongestionServiceTest.java
Labels: 🛠️ 리팩터링, BE

#664 fix: index가 아닌 다른 uri를 찾을 수 없는 에러를 해결한다
  frontend/Dockerfile
  frontend/nginx/conf.d/react.conf
Labels: 🚑 버그, FE

#667 fix: 모바일에서 충전소 리스트가 열리지 않는 오류 수정
  frontend/src/components/ui/StationList/StationListWindow.tsx
Labels: 🚑 버그, FE, 🚨 긴급

#677 feat: PWA(웹앱)으로 카페인 서비스를 이용할 수 있도록 한다
  frontend/nginx/conf.d/react.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/browserconfig.xml
  frontend/public/favicon.ico
  frontend/public/icons/android/android-icon-144x144.png
  frontend/public/icons/android/android-icon-192x192.png
  frontend/public/icons/android/android-icon-48x48.png
  frontend/public/icons/android/android-icon-512x512.png
  frontend/public/icons/android/android-icon-72x72.png
  frontend/public/icons/android/android-icon-96x96.png
  frontend/public/icons/icon-36x36.png
  frontend/public/icons/ios/100.png
  frontend/public/icons/ios/1024.png
  frontend/public/icons/ios/114.png
  frontend/public/icons/ios/120.png
  frontend/public/icons/ios/128.png
  frontend/public/icons/ios/144.png
  frontend/public/icons/ios/152.png
  frontend/public/icons/ios/16.png
  frontend/public/icons/ios/167.png
  frontend/public/icons/ios/180.png
  frontend/public/icons/ios/192.png
  frontend/public/icons/ios/20.png
  frontend/public/icons/ios/256.png
  frontend/public/icons/ios/29.png
  frontend/public/icons/ios/32.png
  frontend/public/icons/ios/40.png
  frontend/public/icons/ios/50.png
  frontend/public/icons/ios/512.png
  frontend/public/icons/ios/57.png
  frontend/public/icons/ios/58.png
  frontend/public/icons/ios/60.png
  frontend/public/icons/ios/64.png
  frontend/public/icons/ios/72.png
  frontend/public/icons/ios/76.png
  frontend/public/icons/ios/80.png
  frontend/public/icons/ios/87.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/pwabuilder-sw.js
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/webpack.config.dev.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🌱 기능추가, FE

#665 refactor: 팝업 메뉴 다른 곳 클릭/축소 확대 하면 자동으로 꺼지게 한다
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/compound/PopupMenu/Menus.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/constants/index.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/stores/popupMenuOpenStore.ts
Labels: 🛠️ 리팩터링, FE

#673 refactor: 충전소 혼잡도가 바로 보이지 않도록 개선한다
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
Labels: 🛠️ 리팩터링, FE, 🚨 긴급

#675 refactor: 충전기 업데이트 날짜에 대한 설명을 수정하고 구조를 개선한다.
  frontend/package.json
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.test.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/constants/chargers.ts
  frontend/src/types/chargers.ts
  frontend/tsconfig.json
Labels: 🛠️ 리팩터링, FE

#681 design: 마커 디자인 및 Layout Shift 개선한다
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#687 refactor: 초기에 basePanel을 닫히도록 수정한다
  frontend/src/stores/layout/navigationBarPanelStore.tsx
Labels: 🛠️ 리팩터링, FE, 🫱🏻‍🫲🏻 페어

#690 feat: 리뷰 조회를 Querydsl 로 변경한다
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReplyController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReplyResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReplyResponses.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
  backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/TotalRatingsResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReplyQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReviewQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/dto/ReplyResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/dto/ReplyResponses.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/dto/ReviewResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/dto/ReviewResponses.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/dto/TotalRatingsResponse.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReplyQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
  backend/src/test/java/com/carffeine/carffeine/helper/MockBeanInjection.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReplyControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/FakeReviewRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReplyFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReviewFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReplyQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReviewQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReplyIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReplyIntegrationTestFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReplyQueryServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewQueryServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
Labels: 🌱 기능추가, BE

#693 fix: 개발 모드에서 pwabuilder-sw 파일 제거한다
  frontend/webpack.config.dev.js
Labels: 🚑 버그, FE, 🚨 긴급

#699 feat: GA4를 적용한다
  frontend/public/index.html
Labels: 🌱 기능추가, FE, 🚨 긴급

#696 refactor: 클라이언트 필터링 클릭 시 추가/해제 되었는지 토스트로 알리는 기능을 추가한다
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/stores/layout/toastStore.tsx
  frontend/src/stores/station-filters/clientStationFiltersStore.ts
Labels: 🛠️ 리팩터링, FE

#700 refactor: 충전소 마커를 덜 요청하도록 개선한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/map/UserFilterListener.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/constants/storageKeys.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/mocks/data.ts
  frontend/src/types/index.ts
  frontend/src/types/map.ts
  frontend/src/types/stations.ts
  frontend/src/utils/getTypedObjectFromEntries.ts
  frontend/src/utils/google-maps/getBounds.ts
  frontend/src/utils/google-maps/index.ts
  frontend/src/utils/google-maps/isCachedRegion.ts
Labels: 🛠️ 리팩터링, FE

#704 refactor: 충전소 마커를 덜 요청하도록 개선한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/map/UserFilterListener.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/constants/storageKeys.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/mocks/data.ts
  frontend/src/types/index.ts
  frontend/src/types/map.ts
  frontend/src/types/stations.ts
  frontend/src/utils/getTypedObjectFromEntries.ts
  frontend/src/utils/google-maps/getBounds.ts
  frontend/src/utils/google-maps/index.ts
  frontend/src/utils/google-maps/isCachedRegion.ts
Labels: FE, 🚨 긴급

#706 refactor: 혼잡도 테이블 파티셔닝 제거
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
  backend/src/main/resources/db/migration/V10__delete_periodic_congestion_partitioning.sql
Labels: 🛠️ 리팩터링, BE

#703 design: 임시로 만들어져 있는 혼잡도 통계 버튼을 개선한다
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ShowHideButton.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerList.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Title.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/src/style/index.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#709 refactor: 혼잡도 통계 API 명세 변경을 적용한다
  frontend/src/components/ui/StationDetailsWindow/StationDetailsView.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionBarContainerSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/src/components/ui/compound/Graph/BarContainer.tsx
  frontend/src/components/ui/compound/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/compound/Graph/DayMenus.tsx
  frontend/src/components/ui/compound/Graph/index.tsx
  frontend/src/constants/congestion.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/station-details/statisticsHandlers.ts
  frontend/src/types/congestion.ts
Labels: 🛠️ 리팩터링, FE

#711 feat: 혼잡도 통계를 설명하는 모달을 구현한다
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/List/List.tsx
  frontend/src/components/common/ListItem/ListItem.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/systems.ts
  frontend/src/components/ui/StationDetailsWindow/congestion/Help.stories.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Help.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Title.tsx
  frontend/src/components/ui/compound/Graph/Bar.tsx
  frontend/src/style/index.ts
  frontend/src/types/style.ts
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE, 🦜 UI

#712 refactor: 모바일 환경에서만 서버 필터링이 자동으로 닫히도록 하는 기능을 구현한다
  frontend/public/index.html
  frontend/src/components/ui/ServerStationFilters/hooks/useStationFilters.ts
Labels: 🛠️ 리팩터링, FE

#715 refactor: 바뀐 검색 api 명세대로 변경한다
  frontend/src/constants/stationSearch.ts
Labels: 🛠️ 리팩터링, FE, 👻 사소한 수정

#716 refactor: `Text` 컴포넌트에 `line-height` 속성 추가 및 적용한다
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/ui/StationDetailsWindow/station/StationInformation.tsx
Labels: 🛠️ 리팩터링, FE

#717 feat: 충전소 리스트 정보를 캐싱할 클래스를 구현한다
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/hooks/useFetchStationSummaries.ts
  frontend/src/components/ui/StationList/tools/cachedStationSummaries.ts
Labels: 🌱 기능추가, FE

#719 feat: 충전소 리스트 정보를 캐싱할 클래스를 구현한다
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/hooks/useFetchStationSummaries.ts
  frontend/src/components/ui/StationList/tools/cachedStationSummaries.ts
Labels: 🛠️ 리팩터링, FE, 🫱🏻‍🫲🏻 페어

#726 fix: 빌드 오류를 개선한다
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🚑 버그, FE, 🚨 긴급

#728 충전소 별 리뷰를 조회하도록 수정한다
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReplyQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReviewQueryRepository.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReplyQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/review/ReviewQueryRepositoryTest.java
Labels: 🚑 버그, BE

#701 refactor: 충전소 및 지역 검색 시 충전기가 아닌 충전소 기준으로 조회되도록 변경한다
  backend/src/docs/asciidoc/station.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/StationInfo.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/StationSearchResponse.java
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationQueryServiceTest.java
Labels: 🛠️ 리팩터링, BE

#733 refactor: 혼잡도 통계에 대한 에러 처리를 한다
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/ui/Error.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
Labels: 🚑 버그, 🛠️ 리팩터링, FE

#734 design: 아이콘을 변경한다
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/NavigationBar/loginMenus.tsx
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#731 test: FE 테스트코드를 보완한다
  frontend/cypress.config.ts
  frontend/cypress/tsconfig.json
  frontend/fileMock.ts
  frontend/jest.config.json
  frontend/jest.setup.ts
  frontend/src/components/ui/Navigator/Navigator.test.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.test.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/StationReportPreConfirmation.render.test.tsx
  frontend/src/components/ui/StationDetailsWindow/reports/station/stationReportConfirmation.render.test.tsx
  frontend/src/components/ui/compound/Graph/Bar.stories.tsx
  frontend/src/components/ui/compound/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/ui/compound/PopupMenu/PopupMenu.stories.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/mocks/handlers/station-filters/serverFilterHandlers.ts
  frontend/src/mocks/node.ts
  frontend/src/stores/station-filters/clientStationFiltersStore.ts
  frontend/tsconfig.json
  frontend/webpack.config.dev.js
  frontend/webpack.config.prod.js
Labels: FE, 👀 테스트

#737 refactor: 마커 렌더링을 최적화 한다
  frontend/src/components/google-maps/marker/Marker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer.tsx
  frontend/src/components/google-maps/marker/hooks/useRenderStationMarker.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/stores/google-maps/markerInstanceStore.ts
Labels: 🛠️ 리팩터링, FE

#742 design: 검색 결과 ux를 개선한다
  frontend/package.json
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/common/systems.ts
  frontend/src/components/ui/Error.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResultSkeleton.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/style/GlobalStyle.ts
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, 🌱 기능추가, FE, 🦜 UI

#743 refactor: 검색 결과로 이동한 지도에서 간단 정보창이 표시되도록 수정한다
  frontend/src/components/google-maps/marker/hooks/useRenderStationMarker.tsx
Labels: 🛠️ 리팩터링, FE

#745 refactor: 혼잡도 그래프 ratio 서버 변경에 맞춰 값 변경한다
  frontend/src/components/ui/StationDetailsWindow/congestion/Help.tsx
Labels: 🚑 버그, 🛠️ 리팩터링, FE, 🚨 긴급

#748 design: 충전소 간단 정보창 상세보기 버튼 모바일에서만 보이도록 개선한다
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/ui/StationSummaryWindow/StationSummaryWindow.tsx
  frontend/src/components/ui/StationSummaryWindow/SummaryButtons.stories.tsx
  frontend/src/components/ui/StationSummaryWindow/SummaryButtons.tsx
  frontend/src/components/ui/StationSummaryWindow/index.tsx
  frontend/src/style/index.ts
Labels: FE, 🦜 UI

#749 fix: 후기 관련 버그를 수정한다
  frontend/public/index.html
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/ReviewPreview.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/previews/UserRatings.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/replies/ReplyList.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewCard.tsx
  frontend/src/components/ui/StationDetailsWindow/reviews/reviews/ReviewList.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/style/GlobalStyle.ts
Labels: 🛠️ 리팩터링, FE, 🚨 긴급

#751 design: 카페인 로고가 모바일 화면에서도 보이고 새로고침 역할을 하도록 개선한다
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/mocks/handlers/station-details/reviews/stationReviewHandlers.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#753 fix: 모바일 환경에서 충전소 리스트 더보기 버튼이 보이지 않는 문제를 해결한다.
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/components/ui/StationList/hooks/useFetchStationSummaries.ts
Labels: 🚑 버그, 🛠️ 리팩터링, FE, 🚨 긴급

#761 refactor: 설문조사 페이지 이동 시 사용자에게 허가를 받도록 개선한다
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/NavigationBar/PersonalMenu.tsx
Labels: 🛠️ 리팩터링, FE

#763 refactor: React.lazy() 를 적용하여 code splitting을 적용한다.
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationList/StationListWindow.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StatisticsGraph/StatisticsGraph.stories.tsx
  frontend/src/components/ui/compound/Graph/Bar.stories.tsx
  frontend/src/router/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.dev.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: 🛠️ 리팩터링, FE

#765 refactor: 충전소 아이디 전역 상태에 의해 제어되는 로직을 개선한다
  frontend/src/components/google-maps/marker/hooks/useRenderStationMarker.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.stories.tsx
  frontend/src/components/ui/StationSearchWindow/SearchResult.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSummaryWindow/StationSummaryWindow.tsx
  frontend/src/hooks/google-maps/useGoogleMap.tsx
  frontend/src/hooks/google-maps/useStationSummary.tsx
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/stores/selectedStationStore.ts
Labels: 🛠️ 리팩터링, FE

#766 refactor: 충전소 혼잡도가 처음부터 보이도록 개선한다
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
Labels: 🛠️ 리팩터링, FE

#770 refactor: 페이지 첫 진입 시 위치 권한을 얻지 않도록 한다
  frontend/src/components/ui/MapController.tsx
  frontend/src/hooks/google-maps/useCurrentPosition.ts
  frontend/src/stores/google-maps/googleMapStore.ts
Labels: 🛠️ 리팩터링, FE

#774 refactor: 모바일 환경에서 충전소 리스트를 클릭하는 경우, 상세보기가 바로 나오지 않고 인포 윈도우가 먼저 뜨도록 한다
  frontend/src/components/ui/StationList/StationSummaryCard.tsx
Labels: 🚑 버그, 🛠️ 리팩터링, FE, 🚨 긴급

#777 design: NavBar 메뉴 UI/UX 개선한다
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/frontend-storybook-deploy.yml
  frontend/src/components/ui/Navigator/Navigator.test.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
Labels: FE, 🦜 UI

#781 refactor: searchWord 전역 상태로 관리하지 않고 prop으로 넘겨주도록 개선한다
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/stores/searchWordStore.ts
Labels: 🛠️ 리팩터링, FE

#786 refactor: tomcat 및 압축 설정
  backend/src/main/resources/application.yml
Labels: 🛠️ 리팩터링, BE

#788 docs: pr template을 변경한다
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/stroybook-link-to-pr-body.yml
Labels: 📖 문서, FE

#791 refactor: 사용하는 폰트 weight만 가져온다
  frontend/public/index.html
Labels: 🛠️ 리팩터링, FE

#792 test: 비어있는 테스트 케이스를 추가한다
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.test.tsx
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/StationList/StationList.tsx
  frontend/src/utils/calculateToastDuration.test.ts
  frontend/src/utils/debounce.test.ts
  frontend/src/utils/external-state/StateManager.test.ts
  frontend/src/utils/external-state/tools.test.tsx
  frontend/src/utils/google-maps/getBounds.test.ts
  frontend/src/utils/google-maps/isCachedRegion.test.ts
  frontend/src/utils/google-maps/isCachedRegion.ts
  frontend/src/utils/request-query-params/getQueryFormattedUrl.test.ts
Labels: FE, 👀 테스트

#795 design: 높아진 NavBar 크기에 맞춰 맵 컨트롤러 등을 위로 올린다
  frontend/public/index.html
  frontend/src/components/common/Toast/ToastContainer.tsx
  frontend/src/components/ui/MapController.tsx
  frontend/src/components/ui/compound/PopupMenu/index.tsx
  frontend/src/style/index.ts
Labels: FE, 🦜 UI

#796 refactor: 충전소 검색 시, 마커의 숫자가 비어있는 현상을 수정한다
  frontend/src/components/ui/CarFfeineMarker/CarFfeineMarker.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/index.tsx
Labels: 🚑 버그, FE, 🚨 긴급

#798 design: 메뉴창 버튼 디자인을 개선한다
  frontend/public/index.html
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/ui/compound/NavigationBar/CloseButton.tsx
  frontend/src/components/ui/compound/NavigationBar/Menu.tsx
Labels: 🚑 버그, 🛠️ 리팩터링, FE, 🦜 UI

#801 refactor: 완속 충전기만 있거나 급속 충전기만 있는 충전소는 혼잡도 완속/급속 버튼을 없앤다
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/ui/StationDetailsWindow/chargers/ChargerCard.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionBarContainerSkeleton.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/CongestionStatistics.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Statistics.tsx
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/components/ui/compound/Graph/CircleDaySelectButton.tsx
  frontend/src/constants/chargers.ts
  frontend/src/constants/congestion.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/mocks/data.ts
  frontend/src/mocks/handlers/station-details/statisticsHandlers.ts
  frontend/src/style/reset.ts
  frontend/src/types/congestion.ts
Labels: 🛠️ 리팩터링, FE, 🦜 UI

#803 refactor: 런타임에서는 서버를 수정할 수 없도록 한다
  frontend/src/components/login/GoogleLogin.tsx
  frontend/src/components/ui/MswControlButton.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useStationFilters.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/modal/CarModal/fetch/index.ts
  frontend/src/constants/server.ts
  frontend/src/hooks/fetch/fetchStationSummaries.ts
  frontend/src/hooks/tanstack-query/car/useCars.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationChargerReport.ts
  frontend/src/hooks/tanstack-query/station-details/reports/useUpdateStationReport.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useCreateReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReplies.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useInfiniteReviews.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useModifyReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReply.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useRemoveReview.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviewRatings.ts
  frontend/src/hooks/tanstack-query/station-details/reviews/useReviews.ts
  frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
  frontend/src/hooks/tanstack-query/station-details/useStationDetails.ts
  frontend/src/hooks/tanstack-query/station-filters/useCarFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useMemberFilters.ts
  frontend/src/hooks/tanstack-query/station-filters/useServerStationFilters.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/hooks/tanstack-query/useSearchedStations.ts
  frontend/src/index.tsx
  frontend/src/stores/config/serverUrlStore.ts
  frontend/src/utils/login/index.ts
  frontend/src/utils/mswModeActions.ts
Labels: 🛠️ 리팩터링, FE

#805 refactor: 클라이언트 코드를 개선한다
  frontend/src/components/common/Loading/Loading.tsx
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/marker/hooks/useRenderStationMarker.tsx
  frontend/src/components/login-page/GoogleLogin.tsx
  frontend/src/components/ui/Navigator/NavigationBar/BasePanel.tsx
  frontend/src/components/ui/Navigator/NavigationBar/CloseButton.tsx
  frontend/src/components/ui/Navigator/NavigationBar/LastPanel.tsx
  frontend/src/components/ui/Navigator/NavigationBar/Menu.tsx
  frontend/src/components/ui/Navigator/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/ui/Navigator/NavigationBar/NavigationBar.tsx
  frontend/src/components/ui/Navigator/NavigationBar/PersonalMenu.tsx
  frontend/src/components/ui/Navigator/NavigationBar/hooks/useNavigationBar.ts
  frontend/src/components/ui/Navigator/NavigationBar/index.tsx
  frontend/src/components/ui/Navigator/Navigator.test.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/Navigator/ProfileMenu/Menus.tsx
  frontend/src/components/ui/Navigator/ProfileMenu/ProfileMenu.stories.tsx
  frontend/src/components/ui/Navigator/ProfileMenu/ProfileMenu.tsx
  frontend/src/components/ui/Navigator/ProfileMenu/index.tsx
  frontend/src/components/ui/ServerStationFilters/ServerStationFilters.tsx
  frontend/src/components/ui/ServerStationFilters/hooks/useStationFilters.ts
  frontend/src/components/ui/StationDetailsWindow/StationDetailsWindow.tsx
  frontend/src/components/ui/StationDetailsWindow/congestion/Help.tsx
  frontend/src/components/ui/StationListWindow/EmptyStationsNotice.tsx
  frontend/src/components/ui/StationListWindow/StationList.tsx
  frontend/src/components/ui/StationListWindow/StationListWindow.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCard.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCardSkeleton.stories.tsx
  frontend/src/components/ui/StationListWindow/StationSummaryCardSkeleton.tsx
  frontend/src/components/ui/StationListWindow/hooks/useFetchStationSummaries.ts
  frontend/src/components/ui/StationListWindow/tools/cachedStationSummaries.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchWindow.tsx
  frontend/src/components/ui/StationSummaryWindow/StationSummaryWindow.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/Bar.stories.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/Bar.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/BarContainer.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/CircleDaySelectButton.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/DayMenus.tsx
  frontend/src/components/ui/StatisticsGraph/Graph/index.tsx
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/router/index.tsx
  frontend/src/stores/popupMenuOpenStore.ts
  frontend/src/stores/profileMenuOpenStore.ts
Labels: 🛠️ 리팩터링, FE, 🫱🏻‍🫲🏻 페어

#807 refactor: 공통 디자인 컴포넌트의 파일 구조를 개선한다
  frontend/src/App.tsx
  frontend/src/components/common/Alert/Alert.style.ts
  frontend/src/components/common/Alert/Alert.tsx
  frontend/src/components/common/Box/Box.style.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.style.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/ButtonNext/ButtonNext.style.ts
  frontend/src/components/common/ButtonNext/ButtonNext.tsx
  frontend/src/components/common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/common/FlexBox/FlexBox.style.ts
  frontend/src/components/common/FlexBox/FlexBox.tsx
  frontend/src/components/common/List/List.style.ts
  frontend/src/components/common/List/List.tsx
  frontend/src/components/common/ListItem/ListItem.style.ts
  frontend/src/components/common/ListItem/ListItem.tsx
  frontend/src/components/common/Loader/Loader.style.ts
  frontend/src/components/common/Loader/Loader.tsx
  frontend/src/components/common/Loading/Loading.tsx
  frontend/src/components/common/Modal/Modal.style.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/SelectBox/SelectBox.style.ts
  frontend/src/components/common/SelectBox/SelectBox.tsx
  frontend/src/components/common/Skeleton/Skeleton.style.ts
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/components/common/Text/Text.stories.tsx
  frontend/src/components/common/Text/Text.style.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/TextField/TextField.style.ts
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.style.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/WarningModal/ZoomWarningModal.tsx
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/login-page/GoogleLogin.tsx
  frontend/src/components/ui/Loading/Loading.stories.tsx
  frontend/src/components/ui/Loading/Loading.style.ts
  frontend/src/components/ui/Loading/Loading.tsx
  frontend/src/components/ui/Loading/index.ts
  frontend/src/components/ui/Navigator/NavigationBar/PersonalMenu.tsx
  frontend/src/components/ui/Navigator/Navigator.test.tsx
  frontend/src/components/ui/Navigator/Navigator.tsx
  frontend/src/components/ui/StatisticsGraph/index.tsx
  frontend/src/components/ui/ToastContainer.tsx
  frontend/src/components/ui/WarningModal/ZoomWarningModal.style.ts
  frontend/src/components/ui/WarningModal/ZoomWarningModal.tsx
  frontend/src/components/ui/WarningModal/index.tsx
Labels: 🛠️ 리팩터링, FE

#810 refactor: 줌 레벨에 따라 다른 api로 요청이 들어갈 수 있도록 마커 컨테이너를 분리한다
  frontend/src/components/google-maps/map/CarFfeineListener.tsx
  frontend/src/components/google-maps/map/CarFfeineMap.tsx
  frontend/src/components/google-maps/marker/CityClusteredMarkersContainer/CityClusteredMarkersContainer.tsx
  frontend/src/components/google-maps/marker/CityClusteredMarkersContainer/index.ts
  frontend/src/components/google-maps/marker/MarkersContainers.tsx
  frontend/src/components/google-maps/marker/ServerClusteredMarkersContainer/ServerClusteredMarkersContainer.tsx
  frontend/src/components/google-maps/marker/ServerClusteredMarkersContainer/index.ts
  frontend/src/components/google-maps/marker/StationMarkersContainer/StationMarkersContainer.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/google-maps/marker/StationMarkersContainer/index.ts
  frontend/src/components/ui/ClientStationFilters.tsx
  frontend/src/components/ui/StationListWindow/tools/cachedStationSummaries.ts
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/constants/googleMaps.ts
  frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
  frontend/src/stores/google-maps/googleMapStore.ts
  frontend/src/stores/google-maps/zoomStore/index.ts
  frontend/src/stores/google-maps/zoomStore/types.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.test.ts
  frontend/src/stores/google-maps/zoomStore/zoomStore.ts
Labels: 🛠️ 리팩터링, FE

#812 refactor: 검색 결과 마커에 사용 가능한 충전기 개수를 로드하는 로직을 개선한다
  frontend/src/components/google-maps/marker/StationMarkersContainer/hooks/useRenderStationMarker.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.stories.tsx
  frontend/src/components/ui/StationSearchWindow/StationSearchBar.tsx
  frontend/src/components/ui/StationSearchWindow/hooks/useStationSearchWindow.tsx
  frontend/src/components/ui/StationSearchWindow/tools/convertStationDetailsToSummary.ts
  frontend/src/hooks/tanstack-query/useSearchStations.ts
Labels: 🛠️ 리팩터링, FE

#814 feat: 도시별 충전소의 개수를 반환하는 기능을 구현한다
  backend/src/docs/asciidoc/station.adoc
  backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/DayConverter.java
  backend/src/main/java/com/carffeine/carffeine/station/domain/station/Region.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/RestTemplateStationRequester.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
  backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/dto/RegionMarker.java
  backend/src/main/java/com/carffeine/carffeine/station/service/charger/ChargerStateUpdateService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationQueryService.java
  backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/carffeine/carffeine/station/controller/station/StationControllerTest.java
  backend/src/test/java/com/carffeine/carffeine/station/fixture/station/StationFixture.java
  backend/src/test/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepositoryTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/congestion/CongestionServiceTest.java
  backend/src/test/java/com/carffeine/carffeine/station/service/station/StationQueryServiceTest.java
Labels: 🌱 기능추가, BE
